### ISSUE TITLE
POST Request Changes Existing Related Row's Foreign Key

### ISSUE THREAD

**Issue by akenn** [jfinkels/flask-restless#153]
Using the [docs example](https://flask-restless.readthedocs.org/en/latest/requestformat.html#post--api-person), when issuing a POST request to insert a new person who has computers that are related to it via a one-to-many relationship, if an existing computer's fields partially match that of the new computer being inserted, then the foreign key of the existing computer will be overwritten with the id of the new person.

In the `post` function in `views.py` (line 1190), `_get_or_create` (on lines 1259 and 1265) gets called to either get the existing computer or insert a new one. If there is a partial match for an existing computer, the scenario described above occurs. I think it should either only switch foreign keys if there is an exact match or just insert a new computer for all POST requests. 

Maybe create a function without the query for an existing row. Something like this (just deleted a few lines from `_get_or_create`):
```python
def _create(session, model, **kwargs):
    instance = model(**kwargs)
    session.add(instance)
    session.flush()
    return instance, True
```
And have that only be for POST requests.

If I'm misinterpreting something and the behavior that currently exists behaves the way it does, can you tell me why? Genuinely curious. Right now I've just implemented the fix I described above and it's working wonderfully. I'm wondering if there's a reason that would be a bad thing.

**Comment by jfinkels** [comment]
We now follow the JSON API protocol for creating and updating resources and relationships, so this is no longer an issue.

**Comment by akenn** [comment]
![amy-seth-snl-high-five](https://cloud.githubusercontent.com/assets/405000/12824060/30881b6e-cb24-11e5-9cf6-2fe37cdc74e7.gif)

**Comment by SheepGotoHeaven** [comment]
Ahaha. I enjoyed that response ^

Nice work jfinkels.
