### ISSUE TITLE
Handle SQLAlchemy exceptions

### ISSUE THREAD

**Issue by eelkeh** [jfinkels/flask-restless#158]
It is possible to provide an exception in the constructor, for instance, when a validation framework is used. When you want restless to handle errors at the DB level, you can provide i.e. SQLAlchemy's `IntegrityError` in the constructor. The `_extract_error_messages` tries to extract a useful error message and pinpoint the invalid field. 
Would it be a useful addition if the `_extract_error_messages` function could parse common SQAlchemy errors when they are provided? 
This might be out of the scope of restless, so it might be better to provide a way to pass on custom exception parsers/handlers. Now it's not possible to handle DB level errors without monkeypatching, as far as I can tell.

The `_extract_error_messages` function could be expanded with something that goes like this:
```python
# Try to catch SQLAlchemy's IntegrityError and parse its message
# for a useful response error.
if isinstance(exception, IntegrityError) and\
    'duplicate key value violates' in exception.message:
    # Parse the error message here...
    # ... and return a useful error message    
    return {'mail': 'already exists'}
````

**Comment by jfinkels** [comment]
We now roll back the session and respond with an error on any subclass of `SQLAlchemyError`; see issue #449. Since the code has changed significantly recently, please open a new issue with a failing test case if this issue still exists.
