### ISSUE TITLE
Allow HTTP delete of sub resources

### ISSUE THREAD

**Issue by chrismckinnel** [jfinkels/flask-restless#193]
At the moment we have to do something like:

    PATCH /model/<id> 

    "relation": {
        "remove": [
            {
                "parent_id": 1,
                "child_id": 1,
                "__delete__": True
            }
        ]
    }

To delete a many to many relation.  Perhaps this has changed slightly on the master branch, but I'm still using the latest tagged release.

Wouldn't it make more sense to be able to a simple:

    DELETE /model/<id>/relation/<id>

Seems like it would simplify things a bit.

Thoughts?

**Comment by jfinkels** [comment]
This is now handled according to the JSON API protocol: http://flask-restless.readthedocs.org/en/latest/updatingrelationships.html
