### ISSUE TITLE
Add Swagger support

### ISSUE THREAD

**Issue by reubano** [jfinkels/flask-restless#206]
https://developers.helloreverb.com/swagger/

Flask peewee and mongodb currently support it. Swagger auto generates docs for your rest api.

**Comment by jfinkels** [comment]
There is at least some support for this at https://github.com/mmessmore/flask-restless-swagger (thanks to @mwhite for the reference). I'm going to close this issue as I prefer it to be supported outside of Flask-Restless itself.
