### ISSUE TITLE
Headers get sent to client as JSON

### ISSUE THREAD

**Issue by raykyri** [jfinkels/flask-restless#214]
When serializing to JSON, Flask-Restless includes the 'headers' object and sends it to the client. This may result in JSON properties you don't want that may be automatically processed by your client:

    {"headers": {"Link": "<http://localhost:5000/api/todos?page=1&results_per_page=-1>; rel=\"last\""}, "todos": [{"is_completed": false, "id": 1, "title": "Meet Ishmael"}, {"is_completed": false, "id": 2, "title": "Do some stuff"}, {"is_completed": false, "id": 4, "title": "More stuff"}, {"is_completed": false, "id": 5, "title": "a"}, {"is_completed": false, "id": 6, "title": "a"}, {"is_completed": false, "id": 7, "title": "b"}, {"is_completed": false, "id": 8, "title": "c"}, {"is_completed": false, "id": 9, "title": "g"}, {"is_completed": false, "id": 10, "title": "a"}, {"is_completed": false, "id": 11, "title": "b"}, {"is_completed": false, "id": 12, "title": "c"}, {"is_completed": false, "id": 13, "title": "a"}]}

There is no way to turn this off because headers are extracted at the end of the jsonpify method. (I'm using Flask-Restless==0.11.0.)

**Comment by jfinkels** [comment]
The master branch now follows the standards from JSON API, so you should no longer see headers in response documents.
