### ISSUE TITLE
Request Super Pre/PostProcessor

### ISSUE THREAD

**Issue by hashg** [jfinkels/flask-restless#235]
I have requirement where all the GET is free. But POST needs to be authenticated. I have around 15+ API's. It becomes painful the add Pre/Postprocessor to each where most of instances it's exactly same operation. Like Authentication check.

Do we have a way to define a generic Pre/Postprocessor directive for all the api's?

**Comment by jfinkels** [comment]
This functionality was added in d2b3789ca103d446bb1f6b23fb49531f4b7723d8.
