### ISSUE TITLE
How to bulk update or delete objects?

### ISSUE THREAD

**Issue by synergetic** [jfinkels/flask-restless#237]
PUT_MANY or PATH_MANY seems to be used when multiple objects updated with the same data. Is it possible to bulk update or delete objects?

**Comment by istinspring** [comment]
this is very usable, for example checkboxes on frontend and then modal Delete Yes/No next one request to the API to delete selected set of items.

**Comment by jfinkels** [comment]
Merged a fix in pull request #393.
