### ISSUE TITLE
Create relationships using array of ids

### ISSUE THREAD

**Issue by joelcox** [jfinkels/flask-restless#243]
Currently Restless requires you to make relationships by passing the related object:

````json
{
  "title": "New post",
  "text": "Lorem ipsum",
  "comments":
  [
    {"id": 1, "name": "Jeffrey", "text": "Restless is awesome!"},
    {"id": 2, "name": "Joel", "text": "Second that"}
  ]
}
````

This makes sense when you're creating the related objects at the same time as the parent object, but not when you're making a relationship between existing objects. Therefore I'd propose adding the functionality to create relationships through passing an array of ids:

````json
{
  "id": 1,
  "tag_ids":
  [
    1,
    2
  ]
}
````

Is this something people would be interested in?

(I'm aware it is possible to passing an array of objects, which only include the id, i.e.: `{"comments": [{"id": 1}, {"id": 2}]}`)

**Comment by jfinkels** [comment]
Flask-Restless now implements the JSON API protocol, so creating and updating relationships happen according to their specification, which is a bit different from the original implementation I had. (Theirs is better.)
