### ISSUE TITLE
Error with  association_proxy of type dict

### ISSUE THREAD

**Issue by Svenito** [jfinkels/flask-restless#244]
If you have an association proxy that uses `_AssociationDict`, `PUT` requests fail.

The issue is with [this line](https://github.com/jfinkels/flask-restless/blob/master/flask_restless/views.py#L1126)

`_AssociationDict` class does not have an `append` function.

The proxy I have created is:

`meta = association_proxy('meta_store', 'value', creator=lambda key, value: Meta(key, value))`

**Comment by jfinkels** [comment]
I'm assuming that this issue was fixed by pull request #247, so I'm closing it.
