### ISSUE TITLE
Getting relation via unique fields as well as primary key

### ISSUE THREAD

**Issue by Svenito** [jfinkels/flask-restless#245]
In `get_or_create` in `helpers.py` any relations in the data are fetched from the primary keys. Is it not also reasonable to fetch relations from columns that are unique?

For example assume:

`data = {'name': 'B. Smith', 'book':{'ISBN': '12345'}}`

Assume that `book` has a primary key `id` and `ISBN` is not a primary key just a unique field. It would be possible to get the `book` object from that uniquely too, which allows us to construct the data without knowing the id of the object. If the ISBN entry doesn't exist, we try to create it.

It wouldn't even have to be all unique fields either, one would suffice to uniquely identify an entry.

If this is a reasonable suggestion, I have a patch for this, but it needs cleaning up and I need to a test case for it.

**Comment by jfinkels** [comment]
Since we now follow the JSON API protocol, I will not add this functionality; resources must be explicitly identifiable by a unique (type, ID) pair.
