### ISSUE TITLE
Relation model view (e.g., /classes/1/students) does not support querying

### ISSUE THREAD

**Issue by thebne** [jfinkels/flask-restless#252]
The `?q= logic` is being exclusively used by the `/tablename/<id>` view, not even once elsewhere.
`/tablename/<id>/relation` does not support any smart filtering.

*I've managed to fix it by passing `relation_value.expression.left == instid` in views.py as filter argument, so it might be not-so-hard to fix.*

**Comment by jfinkels** [comment]
This is now implemented; see `tests/test_filtering.py:TestFiltering.test_to_many_relation` for an example.
