### ISSUE TITLE
include_methods won't exclude those methods from received PUT request

### ISSUE THREAD

**Issue by thebne** [jfinkels/flask-restless#253]
When using `include_methods`, I'd expect these methods to be excluded if sent using PUT/PATCH request - so it won't try updating them.

I've encountered many invalid assignments to class methods (because the json contained my `include_methods)`, which I've managed to fix using a PUT preprocessor to diminish the redundant data. 
However, when calling some relation's method, e.g. `children.name`, it is a bit of a complex logic, requiring me to iterate to the inside of my model in order to pop them out of the query.

**Comment by jfinkels** [comment]
This is fixed by pull request #526.
