### ISSUE TITLE
relation fields and methods

### ISSUE THREAD

**Issue by blurrcat** [jfinkels/flask-restless#258]
We only have control on which fields to return of the model, but no control over what fields to include of a relation of a model. For example, assume we have a team of players and we're creating an API for the player model. The request `/api/player/1/team` would RECURSIVELY load all attributes of the team, which is likely to return sth like:

    {
        "id": 1,
        "score": 1000,
        "additional": "attribute not available at /api/user/1"
        "players": [
            {"id":1, "name": "foo"},
            {"id":2, "name": "bar"},
            ...
         ],
    }

However, I might only want to know the field `additional`, which is not exposed in the response of `/api/player/1`.

In addition, when we make a request to `/api/player/1/team`, we mean "give me information about the TEAM". However, the code(line 1006, views.py) calls :method:`views.API._paginated`, which blindly applies `include_columns` and `include_methods` settings on them. This is wrong because those settings are intended for "player" while the `instances` argument here are actually a "team". What's worse, when the `include_methods` are applied, most probably the program will raise an Attribute error, because `Team` doesn't have `Player`'s methods.

Could you save the world by adding some settings for the relation, like `relation_include_columns` and `relation_include_methods`?

**Comment by jfinkels** [comment]
There were really a couple issues here, but the main one is serialization of related resources, which is fixed now: Flask-Restless implements the JSON API specification in which relationships are not serialized but exist only as references.
