### ISSUE TITLE
No way to do UPSERT using PUT

### ISSUE THREAD

**Issue by qrilka** [jfinkels/flask-restless#261]
According to HTTP spec it is possible to create new resource by PUTting to its desired URI - http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6   :

>The PUT method requests that the enclosed entity be stored under the supplied Request-URI. If the Request-URI refers to an already existing resource, the enclosed entity SHOULD be considered as a modified version of the one residing on the origin server. If the Request-URI does not point to an existing resource, and that URI is capable of being defined as a new resource by the requesting user agent, the origin server can create the resource with that URI. 

And it's not possible with flask-restless as it requires table row to be already present:
```python
# create a SQLAlchemy Query which has exactly the specified row
query = query_by_primary_key(self.session, self.model, instid)
if query.count() == 0:
    abort(404)
```

**Comment by jfinkels** [comment]
This is no longer relevant, since Flask-Restless now follows the JSON API specification, which only allows POST and PATCH requests.

**Comment by qrilka** [comment]
@jfinkels if so, shouldn't it appear on http://jsonapi.org/implementations/ ?

**Comment by jfinkels** [comment]
Technically, the code implementing JSON API is not released yet. I'd like to release at least a beta version before submitting the project to that list.

**Comment by jfinkels** [comment]
In any case, I just created issue #489 for tracking that issue.
