### ISSUE TITLE
Create many objects

### ISSUE THREAD

**Issue by sn0rcha** [jfinkels/flask-restless#262]
I was wondering if it's possible to post an array of objects rather then just a single object to an API endpoint and have it create multiple objects?

Many thanks, Ben

**Comment by drmclean** [comment]
Is there any documentation anywhere of how to post multiple records to my Flask Restless API at the same time?

**Comment by jfinkels** [comment]
Since Flask-Restless now implements the JSON API specification, this issue is a part of issue #477. Please continue any discussion there.
