### ISSUE TITLE
POST postprocessor can affect generated URL

### ISSUE THREAD

**Issue by drwlrsn** [jfinkels/flask-restless#266]
Hey just to start: thanks so much for your hard work with this project. I very much appreciate it because it makes my life easier.

On a sadder note: the issue is if in the POST postprocessor one modifies the result so the primary key is moved out of the first 'level' of the dict, the URL for that newly instance can't be constructed. In `views.py`:
```
for postprocessor in self.postprocessors['POST']:
    postprocessor(result=result)

# The URL at which a client can access the newly created instance
# of the model.
primary_key = primary_key_name(instance)
url = '%s/%s' % (request.base_url, result[primary_key])
# Provide that URL in the Location header in the response.
headers = dict(Location=url)
return jsonify_status_code(201, headers=headers, **result)
```
As you can see the postprocessors are applied before the URL and headers are constructed. Which means if you have a postprocessor that looks something like this:
```
def api_post_post(result=None, **kw):
    temp = copy.deepcopy(result)
    result.clear()
    result['object'] = temp
```
This will result in the error:
```
  File ".../flask_restless/views.py", line 1144, in post
    url = '%s/%s' % (request.base_url, result[primary_key])
KeyError: 'id'
```
I'll fork, fix and submit a pull request in the next 24 hours. Is there anything else I need to do to get a PR merged?

**Comment by jfinkels** [comment]
I am going to close this because it is old and I suspect the issue may have been fixed.
