### ISSUE TITLE
Add ability to get the entire schema

### ISSUE THREAD

**Issue by mwhite** [jfinkels/flask-restless#268]
For clients that dynamically build an interface based off of the table definitions, they would need to be able to get all the tables, columns, and relationships.

There could be a single API call that returns the entire schema, or each table could have its own call with pointers to related tables.

Any thoughts on the best way to do this? I'm thinking of doing this soon for a project.

**Comment by roemhildtg** [comment]
I really would find this feature valuable. I've been working on a flask-restless client for canjs and I'm currently creating a custom endpoint that handles this using https://github.com/mattupstate/flask-jsonschema, but if it were built into `/api` that would be more maintainable. 

Along with exposing each table's fields and types, it could also provide a count of how many features are in each table. This would allow clients to generate pagination. Currently the only way to find out how many features there are is to query the endpoint for results.

**Comment by jfinkels** [comment]
Pull request #580 is a first draft implementation of this.

**Comment by jfinkels** [comment]
I merged pull request #580, so this should be available in the development version.
