### ISSUE TITLE
Search query for <relationname>__<fieldname>.

### ISSUE THREAD

**Issue by rday** [jfinkels/flask-restless#272]
I'm trying to create a search query using the relationname__fieldname pattern. I am querying for all forms owned by a certain user as the username is being typed in the UI:

/api/form?q={"name": "owner__user_name", "op":"ilike", "val": "%Joh%"}

```
class User(db.Model):
   user_id = db.Column(db.Integer)
   user_name = db.Column(db.String)

class Form(db.Model):
    owner_id = db.Column(db.Integer, db.ForeignKey('user.user_id')
    owner = db.relationship('User')
```

I'd like this to provide me with the forms owned by users matching the ilike query.

However I'm getting an 
```
NotImplementedError: <function ilike_op at 0x1652668>
```

When I try to debug this, it looks like the ilike operator (from OPERATORS in search.py) is trying compare Form.owner to %Joh% instead of trying to compare Form.owner.user_name to %Joh%. This is happening on line 348 in flask_restless/search.py.

I'm wondering if I'm using this search query incorrectly, or if there may be a bug in this particular functionality. Thanks!

**Comment by jfinkels** [comment]
I have expanded the documentation with just a little bit more of an explanation on using `has` and `any`: http://flask-restless.readthedocs.org/en/latest/searchformat.html#using-has-and-any

Is the section before that <http://flask-restless.readthedocs.org/en/latest/searchformat.html#comparing-attribute-of-a-relation> unnecessary? If we can use has and any in the way suggested here, why do we need this double-underscore way of accessing relations?

**Comment by jfinkels** [comment]
This should be fixed/clearer in the new version of the documentation: http://flask-restless.readthedocs.org/en/latest/fetching.html#using-has-and-any

The underscore no longer exists.
