### ISSUE TITLE
url_for api generated endpoints

### ISSUE THREAD

**Issue by michaelfillier** [jfinkels/flask-restless#274]
I needed to create a custom route for some complex logic in the app, I am actually returning a 303 since the endpoint performs an update on another object. A 303 is supposed to return a location for the browser or client to know the url of the updated resource, which they can then use to request the object, if needed.

I would like to return the url of the updated object and thought it would be nice to have a shortcut to the GET SINGLE url for the resource. How do you normally refer to your endpoint urls when referring to them throughout your app? Typing them out is simple enough, but if the urls change, whether via an updated prefix or perhaps a model name change, it would be nice if I could simply refer to the endpoint by name and pass in the id, eg api_endpoint(people_get_single, 1).

Any thoughts?

**Comment by jfinkels** [comment]
This is implemented in 905b4d6793c85e795bcfa2c3a9be619ca25a00e2. I'm positive there will be some bugs with it, so please test it out.
