### ISSUE TITLE
Add Calculated Fields To Response

### ISSUE THREAD

**Issue by rholloway** [jfinkels/flask-restless#302]
I have noticed if we use a calculated field for a SQLAlchemy model (using `@property`), Flask-Restless is unable to return these fields when a request is made to `/api/model/<id>`, and I haven't seen a way to enable it either.

The only workaround I have is using a post-processor and manually grab those calculated values and append to the json response.

Having a way to specify to Flask-Restless to go ahead and do this would be nice, since the workaround requires the postprocessor to be modified on a per-model basis.

**Comment by jfinkels** [comment]
Is this fixed by #386? I think you'll still have to explicitly include these properties.

**Comment by jfinkels** [comment]
This should be fixed by the `additional_attributes` keyword argument to the `APIManager.create_api` method which now appears on the master branch.
