### ISSUE TITLE
Ability To Specify Recursion Level

### ISSUE THREAD

**Issue by rholloway** [jfinkels/flask-restless#303]
I noticed that by default Flask-Restless only returns one level of recursion on relationships. That is, a request to /api/model/<id> returns that models immediate attributes, the relationships and their immediate attributes, but does not return relationships on relationships or so forth. 

It's possible to make a second request to pull these, such as /api/model/<id>/relationship which will then give you that second level, but each one will require setting up additional requests.

The main issue here is when we want to pull a big block of data and all the information we can on a model using asynchronous javascript, we have to code up several levels of asynchronous AJAX requests to get at the information. If we could specify how many levels of recursion we wanted with the first request, we could just get one big JSON blob in a single request containing all data. In my opinion, one much larger JSON blob may take longer to serve, but in a highly normalized database where there are many different joins and relationships going on, it'll be much preferred both for performance and coding (much fewer code to make a single AJAX call than multiple async calls, browsers tend to only send out 2-3 requests at once while waiting for responses, introducing latency as more and more ajax calls are stacked, etc).

I realize that probably the primary concern here is with infinite loops being setup if back references exist. The easiest solution would be to simply leave those out and not include those relationships during the recursion, since the information will be available higher up in the JSON hierarchy. 

Also, depending on the amount of data and relationships for a given model, it could return more than is needed, so that is where a parameter specifying recursion level would be helpful.

The alternative to pragmatically determining when a back reference occurs would be an option to allow users to explicitly specify which relationships should be recursed somewhere. For example, users add something like __recurse_relations__ attribute to the SQLAlchemy model that specifies which relationships can be recursed safely. It makes the work of figuring it out automatically a little easier, but does require extra work on the users since they must specify which ones should automatically recurse.

**Comment by jfinkels** [comment]
Flask-Restless now supports JSON API. The default recursion level is therefore...0. Related resources can be included using the `include` query parameter on the client-side.

http://flask-restless.readthedocs.org/en/latest/fetching.html#inclusion-of-related-resources

**Comment by psotoulloa** [comment]
Hi, i tried this using the 0.17 versión but it doesn't work
I notice also this functionality is not in the change log of this version
When we can use it?

**Comment by jfinkels** [comment]
It will be released in version 1.0.0-beta1, which is not released yet on PyPI. You can try it by installing from directly from the git repository.

**Comment by eliaperantoni** [comment]
Any updates on this? Is it possible at  the moment to specify how deep to go with recursion?
