### ISSUE TITLE
Managing models with many-to-many relationships

### ISSUE THREAD

**Issue by sssilver** [jfinkels/flask-restless#321]
The documentation seems to lack any detail about how to properly utilize flask-restless to manage models with many-to-many relationships.

**Comment by lustlost** [comment]
I can not find section of use of many-to-many relationships in documentation,can give me a document link ? @jfinkels

**Comment by jfinkels** [comment]
This issue remains unfixed: there is no such documentation. I have recently updated Flask-Restless to use the JSON API protocol (on the `master` branch), and have not yet solved all the issues with association proxies (see issue #480) which is a first step to managing many-to-many relationships. If anyone can help there, then I can make progress on this issue.

**Comment by jfinkels** [comment]
There is now some documentation about how to use association proxies to manage many-to-many relationships. See https://flask-restless.readthedocs.io/en/latest/databasesetup.html#id1

If you have any more specific issues with the documentation (which is certainly still lacking!), please open a new issue.
