### ISSUE TITLE
<relationname>__<fieldname> syntax for order_by in queries

### ISSUE THREAD

**Issue by rikrd** [jfinkels/flask-restless#327]
In the case of the filters of a query we can impose conditions on relationships by doing this:

<relationname>__<fieldname>

https://flask-restless.readthedocs.org/en/latest/searchformat.html#queryformat

I was wondering if something similar could be done for the case of order_by. If for instance we would want to sort the results by computers__manufacturer

**Comment by rcomblen** [comment]
+1, we miss that feature.

**Comment by jfinkels** [comment]
Fixed by #327.
