### ISSUE TITLE
like operator doesn't behave as expected in 0.12.1

### ISSUE THREAD

**Issue by LordSputnik** [jfinkels/flask-restless#331]
This occurs in flask-restless 0.12.1.

Recently, I attempted to do the following query through my flask-restless API:
http://waveplot.net/api/release?q={"filters":[{"name":"title","op":"like","val":"%ce%"}]}

This returns no results. However, when doing a slightly different query, using "Place" or just "c", I do get results:
http://waveplot.net/api/release?q={"filters":[{"name":"title","op":"like","val":"%Place%"}]}
http://waveplot.net/api/release?q={"filters":[{"name":"title","op":"like","val":"%c%"}]}

And similarly, performing the following on my database also yields results:
"SELECT * FROM release WHERE title LIKE '%ce%';"

I would expect results from the first query to match the results returned from the SQL expression, or at least to contain a superset of the results from my second query to the API. The fact that no results are returned indicates something may be going wrong.

The site is live, if you'd like to test any other combinations. If you would like any further specific info, I can try to get that too.

**Comment by jfinkels** [comment]
Closing this due to lack of minimum working example.
