### ISSUE TITLE
What is the best way to handle Files included in a post request?

### ISSUE THREAD

**Issue by surbas** [jfinkels/flask-restless#341]
Hello,

I been banging my head trying to figure out the best way to post a file to an endpoint.

Ideally i want to handle the metadata (name, date, user) associated with the file/files all in one request. The files would be in the original binary format when they hit the end point, with an mime type associated with them. I believe this is how imgur api works.

I am now going down the path of base64ing the files before making the request. This seems wasteful to me (33% increase in file size and associated processing time) and wanted to know if there was a better way to reach my ideal? I tried hooking into post via preprocessor arg, but the preprocessors run after the request data is transformed from json... If i wanted to hook the view before any processing is done is the best way via #318? That seems even more kludgy. Would it make sense to add another preprocessor hook like "prepreprocessor" or "contentprocessor" which would be responsible for returning cleaned `params` (see def of post in views.py)?

My ideal may be wrong approach and would like to know you guys think?

Thanks
Shon

**Comment by sholsapp** [comment]
> Being able to add handling of multipart/form-data for this one endpoint this would make what I am doing easier.

@surbas I agree and am looking to do the same thing. Did you end up forking and adding this functionality? If so, do you mind sharing that information here?
