### ISSUE TITLE
Changing instance_id on GET request via preprocessor does not work

### ISSUE THREAD

**Issue by h0st1le** [jfinkels/flask-restless#365]
The documentation states: ' Preprocessors and postprocessors modify their arguments in-place.'

However, if I attempt to change the instance_id on a GET request it does not work. Although it appears to change the argument in-place, it does not return the changed id. Instead the original id requested, is used and the preprocessor modification is ignored.

I modified quickstart.py to give a working example below:

    import os
    import flask
    import flask.ext.sqlalchemy
    import flask.ext.restless

    from datetime import datetime

    _basedir = os.path.dirname(os.path.abspath(__file__))

    # Create the Flask application and the Flask-SQLAlchemy object.
    app = flask.Flask(__name__)
    app.config['DEBUG'] = True
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + _basedir + '/test.sqlite'
    db = flask.ext.sqlalchemy.SQLAlchemy(app)

    # Create your Flask-SQLALchemy models as usual but with the following two
    # (reasonable) restrictions:
    #   1. They must have a primary key column of type sqlalchemy.Integer or
    #      type sqlalchemy.Unicode.
    #   2. They must have an __init__ method which accepts keyword arguments for
    #      all columns (the constructor in flask.ext.sqlalchemy.SQLAlchemy.Model
    #      supplies such a method, so you don't need to declare a new one).

    class Person(db.Model):
        id = db.Column(db.Integer, primary_key=True)
        name = db.Column(db.Unicode)
        birth_date = db.Column(db.Date)

    class Computer(db.Model):
        id = db.Column(db.Integer, primary_key=True)
        name = db.Column(db.Unicode)
        vendor = db.Column(db.Unicode)
        purchase_time = db.Column(db.DateTime)
        owner_id = db.Column(db.Integer, db.ForeignKey('person.id'))
        owner = db.relationship('Person', backref=db.backref('computers',
                                                             lazy='dynamic'))

    # Create the database tables.
    db.create_all()

    p1 = Person(name=u'Bob', birth_date=datetime.strptime('1980-12-14T05:00:00.000Z', '%Y-%m-%dT%H:%M:%S.%fZ'))
    db.session.add(p1)

    p2 = Person(name=u'Jim', birth_date=datetime.strptime('1982-08-22T05:00:00.000Z', '%Y-%m-%dT%H:%M:%S.%fZ'))
    db.session.add(p2)

    c1 = Computer(name=u'Bobs Computer', vendor=u'ASUS', purchase_time=datetime.strptime('2013-10-15T05:00:00.000Z', '%Y-%m-%dT%H:%M:%S.%fZ'), owner=p1)
    db.session.add(c1)

    c2 = Computer(name=u'Jims Computer', vendor=u'Apple', purchase_time=datetime.strptime('2013-08-22T05:00:00.000Z', '%Y-%m-%dT%H:%M:%S.%fZ'), owner=p2)
    db.session.add(c2)
    db.session.commit()

    # Create the Flask-Restless API manager.
    manager = flask.ext.restless.APIManager(app, flask_sqlalchemy_db=db)

    def pre_get_single(instance_id=None, **kw):
        if instance_id == u'1':
            # "change instance_id from one to two"
            instance_id = u'2'
        else:
            # "change instance_id from two to one"
            instance_id = u'1'
        print instance_id

    # Create API endpoints, which will be available at /api/<tablename> by
    # default. Allowed HTTP methods can be specified as well.
    manager.create_api(Person,
            methods=['GET', 'POST', 'DELETE'],
            preprocessors={
                'GET_SINGLE': [pre_get_single]
                }
            )
    manager.create_api(Computer, methods=['GET'])

    # start the flask loop
    app.run()

**Comment by jfinkels** [comment]
The requested functionality will appear in version 0.16.0. See pull request #390.
