### ISSUE TITLE
Any SQL exception causes session to into invalid transaction permanently

### ISSUE THREAD

**Issue by sveint** [jfinkels/flask-restless#370]
Concerning: flask-restless 0.15.0

This could be user error, but whenever there's a database error, the whole REST framework goes into an unusable state since the session is never rolled back.

Setting up APIManager like this:

    APIManager(myApp, session=mySession)

For instance, restarting the DB gives this:

    StatementError: Can't reconnect until invalid transaction is rolled back (original cause: InvalidRequestError: Can't reconnect until invalid transaction is rolled back) u'SELECT count(*) AS count_1 \nFROM sample' [{}]

This applies for any exception happening at database level, for instance faulty SQL statements (e.g. giving a page outside valid range for pagination giving negative LIMIT, but that's another bug I guess).

I cannot find anywhere in the documentation mentioning manual exception handling for the requests. Is this a bug or am I doing something wrong?

**Comment by jfinkels** [comment]
Perhaps this is fixed by commit e4f802d345fb75e2453fe88b971451966dadf98d, which appears in version 0.15.1-dev?

**Comment by jfinkels** [comment]
The documentation now states briefly that certain types of exceptions will cause a session rollback: http://flask-restless.readthedocs.org/en/latest/requestformat.html#errors-and-error-messages

As stated in my previous comment, please test version 0.15.1 or later and let me know if this is still an issue.

**Comment by jfinkels** [comment]
We now catch any `SQLAlchemyError` and roll back the session, so this should be fixed. See issue #449.
