### ISSUE TITLE
Cannot use limit if offset is 0 in query string (issue in 0.13.1, fixed in 0.15.1)

### ISSUE THREAD

**Issue by rcomblen** [jfinkels/flask-restless#378]
Hi,

I want to do client side pagination. I disable pagination on Flask-Restless, and query using `?q={limit:XXX,offset:XXX}`

if offset is > 0 all works fine. If offset is 0, limit is not taken into account anymore. Please have a look at the minimal example ( https://github.com/rcomblen/flask_restless_limit_issue ), it's based on the QuickStart example:

correct behavior:

    GET http://localhost:5000/api/person?q={"limit": 5, "offset": 1} => size is 5

wrong behavior:

    GET http://localhost:5000/api/person?q={"limit": 5, "offset": 0}  => size is 30

SQL output is

    INFO:sqlalchemy.engine.base.Engine:SELECT count(*) AS count_1 
    FROM person
     LIMIT ? OFFSET ?
    INFO:sqlalchemy.engine.base.Engine:(5, 0)
    INFO:sqlalchemy.engine.base.Engine:SELECT person.id AS person_id 
    FROM person ORDER BY person.id ASC
     LIMIT ? OFFSET ?
    INFO:sqlalchemy.engine.base.Engine:(30, 0)

The 30 in the line above should be 5

    INFO:sqlalchemy.engine.base.Engine:ROLLBACK
    INFO:sqlalchemy.engine.base.Engine:BEGIN (implicit)
    INFO:sqlalchemy.engine.base.Engine:SELECT count(*) AS count_1 
    FROM person
     LIMIT ? OFFSET ?
    INFO:sqlalchemy.engine.base.Engine:(5, 1)
    INFO:sqlalchemy.engine.base.Engine:SELECT count(*) AS count_1 
    FROM (SELECT person.id AS person_id 
    FROM person ORDER BY person.id ASC
     LIMIT ? OFFSET ?) AS anon_1
    INFO:sqlalchemy.engine.base.Engine:(5, 1)
    INFO:sqlalchemy.engine.base.Engine:SELECT person.id AS person_id 
    FROM person ORDER BY person.id ASC
     LIMIT ? OFFSET ?
    INFO:sqlalchemy.engine.base.Engine:(5, 1)

I have the issue with both SQLite and PostgreSQL drivers.

**Comment by doobeh** [comment]
Your project seems to work as expected for me:
	
#### Versions

	Flask 0.10.1
	Flask-Restless 0.15.1
	Flask-SQLAlchemy 2.0
	SQLAlchemy 0.9.8

#### Output

	http://localhost:5000/api/person?q={"limit": 5, "offset": 0}
	this should be 5:
	5
	http://localhost:5000/api/person?q={"limit": 5, "offset": 1}
	this should be 5:
	5

**Comment by rcomblen** [comment]
Hi,

issue is there with Flask-Restless 0.13.1 and not with 0.15.1, so we'll just update.
BTW, why isn't there tag on this repository for version after 0.13.1 ? Is that on purpose ? It was misleading for me, as I just thought 0.13.1 was the latest release, as it was the latest tag. I should have looked on pypi ...

**Comment by jfinkels** [comment]
There's no tag because I forgot to push the tags from my local machine up to the GitHub repository. I've updated my release script so that it reminds me to do that...
