### ISSUE TITLE
preprocessors on relationship collections

### ISSUE THREAD

**Issue by chaitan94** [jfinkels/flask-restless#381]
Requesting for `GET /api/computers`,  one could easily format the response using GET_MANY preprocessor, but it's not yet possible to do the same with relationship collections like `GET /api/person/(int: id)/computers`. I think it might be helpful to implement it for these situations as well, currently I'm sure how I can implement this, but it would really helpful if anyone can figure it out.

**Comment by jfinkels** [comment]
This is now implemented in the development branch.
