### ISSUE TITLE
Conflicting documentation and implementation of collection_name 

### ISSUE THREAD

**Issue by Kha** [jfinkels/flask-restless#382]
`docs/customizing.rst`:
> If your model is a SQLAlchemy model, this will be the value of __tablename__. If your model is a Flask-SQLAlchemy model, this will be the lowercase name of the model with CamelCase changed to camel_case.

`create_api_blueprint` docstring:
> If `collection_name` is ``None``, the lowercase name of the provided model class will be used instead, as accessed by ``model.__name__``. (If any black magic was performed on ``model.__name__``, this will be reflected in the endpoint URL.)
> [...]
> If this is not specified, the lowercase name of the model will be used.

actual implementation:
```
if collection_name is None:
    collection_name = model.__tablename__
```

**Comment by jfinkels** [comment]
So not only do they conflict, but neither of them is exactly correct!

I'll take a look at this now.

**Comment by jfinkels** [comment]
Fixed.
