### ISSUE TITLE
Make 'include_methods' work on non-callable properties

### ISSUE THREAD

**Issue by Romainpaulus** [jfinkels/flask-restless#385]
I have defined a few properties in my models with the `@property` decorator, and I would like to include them in the models representation. Unfortunately, `include_columns` only works for callable methods, and `include_columns` only works for database columns.
This would a small change in the flask-restless code, and I'm ready to submit a pull request, I just wanted to know if that's a reasonable change to make.

**Comment by jfinkels** [comment]
Sounds reasonable to me.

**Comment by jfinkels** [comment]
This is fixed by pull request #386.
