### ISSUE TITLE
Include property values in results

### ISSUE THREAD

**Issue by Xion** [jfinkels/flask-restless#388]
`APIManager.create_api` supports `include_methods` argument which allows to add return values of arbitrary model methods to the response. It only work on actual methods, whereas the pythonic pattern of including additional data attributes on classes is to rather use properties than getter/setter methods.

Thus I suggest introducing a new parameter to `create_api`, `include_attributes`, where the user can list names of arbitrary attributes to include in the response. Properties could be readily included in such a list.

**Comment by drmclean** [comment]
doesn't "include columns" do this?

**Comment by Xion** [comment]
Nope. `include_columns` is only used to filter columns on the model -- see https://github.com/jfinkels/flask-restless/blob/master/flask_restless/helpers.py#L325 and above.

**Comment by jfinkels** [comment]
Does #386 fix this?

**Comment by Xion** [comment]
Yes, that works :) Though I think `include_methods` is weird parameter name in this case, so perhaps some API cleanup would be in order here. But that's outside of the scope of this issue, of course.

**Comment by jfinkels** [comment]
I guess the other option would be `include_attributes` which is equally confusing. If you come up with a good name for that keyword argument, let me know (in a new issue).
