### ISSUE TITLE
Follow the standards at jsonapi.org

### ISSUE THREAD

**Issue by jfinkels** [jfinkels/flask-restless#394]
http://jsonapi.org/ proposes a standard for creating JSON API. We should follow that (and state that fact explicitly).

This will resolve issue #214 as well.

**Comment by emilecaron** [comment]
What is the status of this issue? is there any plan to releas jsonapi compatibility here or in a fork ?
I can't seem to find any information about it.

**Comment by jfinkels** [comment]
Sorry for the lack of updates (here and on other issues)!

You can see my progress in pull request #404. I have essentially rewritten everything to be compliant with the core part of the JSONAPI 1.0 specification. You can see the tests for JSONAPI compliance in the `tests/test_jsonapi` package in that pull request (or equivalently, on the branch `jsonapi`). The remaining bugs concern the use of association proxies, and I don't know how to solve those problems. I am tempted to just pull those changes into master as a sort of "beta" release and hope that someone wiser than me can fix the problems I'm having with the association proxies.

**Comment by sholsapp** [comment]
+1 - I would love to see this to simplify integrating an Ember.js frontend with a Flask-Restless backend.

**Comment by jfinkels** [comment]
This is done on the master branch. I will release a version 1.0.0-beta1 so people can use it.

**Comment by sholsapp** [comment]
Sweet. Once we get a release to PyPI I can help test it out.
