### ISSUE TITLE
DELETE is either wrong in the code or in the docs

### ISSUE THREAD

**Issue by jwanglof** [jfinkels/flask-restless#398]
In the latest docs (0.16.1-dev) it clearly states that:

> Changed in version 0.16.0: Replaced DELETE with DELETE_MANY and DELETE_SINGLE.

However, when I insert a pre- or post-processor to DELETE_SINGLE nothing is happening, either before the request or after. When I looked in the tests for 0.16.0 (granted, this is not the latest but the docs says 0.16.0 and the latest official release is 0.16.0) it tests against DELETE and not DELETE_SINGLE

Line 217 in tests/test_processors.py:
```
pre = dict(DELETE=[check_permissions])
```
This should be changed to DELETE_SINGLE to correlate with the documents, or the document should change from DELETE_SINGLE to DELETE.

**Comment by jfinkels** [comment]
Yes, this is a bug. That's my bad, sorry! I'll fix it right away.

**Comment by jfinkels** [comment]
This is fixed by 79ea9a44e88dc97a7e10f9f9bf6ea0bed68ba7b1.
