### ISSUE TITLE
Mishandling of session.commit() exceptions

### ISSUE THREAD

**Issue by sssilver** [jfinkels/flask-restless#402]
The call to `self.session.commit()` in views.py:1384 may potentially fail due to many reasons (a common reason being `FlushError`). However, these failures are not properly handled with a `rollback()`, which causes all subsequent queries to the session to fail with:

> `InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback().`

**Comment by jfinkels** [comment]
Would this be fixed by being more liberal with what exceptions are caught in the `catch_integrity_errors` decorator? For example, changing

            try:                                                                
                return func(*args, **kw)                                        
            except (DataError, IntegrityError, ProgrammingError) as exception:  
                session.rollback()                                              
                current_app.logger.exception(str(exception))                    
                return dict(message=type(exception).__name__), 400              

to

            try:                                                                
                return func(*args, **kw)                                        
            except Exception as exception:  
                session.rollback()                                              
                current_app.logger.exception(str(exception))                    
                return dict(message=type(exception).__name__), 400

**Comment by sssilver** [comment]
Seems like that would work, at least this for this particular situation.
However a more seasoned SQLAlchemy developer might have a more idiomatic
solution / approach.

**Comment by manuhk** [comment]
This is impacting me too because of a basic UnicodeEncodeError: all subsequent transactions fail because of this error...
Catching al exceptions appear to me as a good solution, but for sure I'm not a seasoned SQLAlchemy developer!

**Comment by jfinkels** [comment]
We now catch any `SQLAlchemyError` and roll back the session, so this should be fixed. See issue #449.

See also issue #370.
