### ISSUE TITLE
Marshmallow serializer integration

### ISSUE THREAD

**Issue by taion** [jfinkels/flask-restless#407]
The current `include_columns`/`exclude_columns` plus postprocessor paradigm is great for getting something up and running.

However, for richer use cases, it's common to have support for serialization as an explicit extra step. There's a package called marshmallow that serves this purpose and is analogous to serializers in Django REST Framework: http://marshmallow.readthedocs.org/en/latest/

It would make sense to allow specifying a marshmallow serializer as an alternative to the existing include/exclude column options, for when the user needs more control over serialization (and wishes to do so in a generic way).

**Comment by jfinkels** [comment]
Well, the particular serialization function doesn't matter; it could be marshmallow, or another library, or my own homemade function. What you're asking for here is to allow the user to specify an arbitrary serialization function, call it `dump`, which will be called immediately before `jsonify` is called. That has already been requested in #167, so I'm going to close this issue and restart the conversation there.
