### ISSUE TITLE
Blueprint object has no attribute after_request

### ISSUE THREAD

**Issue by SergeyAlexeev** [jfinkels/flask-restless#410]
I've tried to enable CORS in my Flask-Restless app. I've found this article http://flask-restless.readthedocs.org/en/latest/customizing.html#enabling-cross-origin-resource-sharing-cors and tried to use information from 'Enabling Cross-Origin Resource Sharing (CORS)' paragraph. Unfortunately, I've had an error - blueprint object has no attribute after_request. Next, I've asked about this issue in StackOverflow, http://stackoverflow.com/questions/28569362/flask-restless-manager-create-api-does-not-return-blueprint-object, but nobody has answered yet. Some time ago I've found the same question http://stackoverflow.com/questions/28698948/how-to-enable-cors-with-flask-restless. So, it looks like a bug.

**Comment by agumonkey** [comment]
I too hit this issue. create_api(...) returns None. It's possible to bypass the manager and hook into the app instance directly, in case someone doesn't want to use the Flask-CORS extension (http://flask-cors.readthedocs.org/en/latest/)
```
manager = flask.ext.restless.APIManager(app, flask_sqlalchemy_db=db)
# lines from the docs that won't work
# blueprint = manager.create_api(Doc, methods=['GET', 'POST', 'DELETE'])
# blueprint.after_request(add_cors_headers)

# ~hack
app.after_request(add_cors_headers)
```

**before**
```
$ curl -v localhost:5000/api/doc |& grep Allow-Origin
```
**after**
```
$ curl -v localhost:5000/api/doc |& grep Allow-Origin
< Access-Control-Allow-Origin: *
```

**Comment by jfinkels** [comment]
Use `manager.create_api_blueprint` to create a blueprint, not `create_api`.

**Comment by jfinkels** [comment]
This is fixed in the documentation.
