### ISSUE TITLE
Feature request: Complex routes (e.g. “forgot password”)

### ISSUE THREAD

**Issue by grulg** [jfinkels/flask-restless#411]
I wish to make a route for "forgot password"-functionality. My idea was that the request could look like this

    POST /api/user/<id>/forgot_password

and Flask-Restless would send this request to a custom "forgot password"-route which I provided. This way, I could define my own complex operations on the user object (store intermediate stuff in DB, email password reset link, etc). You could also imagine this scenario for e.g. change email, forgot password as well.

I flagged this as a feature request, as I couldn't find anyway of doing this in the documentation. If there are better solutions, I'd gladly take those.

(Created a SO-question without any success: http://stackoverflow.com/questions/28637420/complex-routes-for-flask-restless-e-g-forgot-password)

**Comment by jfinkels** [comment]
Hmm, this complex behavior seems a bit beyond the scope of Flask-Restless. This library is intended to be a simple way to expose resources backed by SQLAlchemy models in a RESTful way. The route `/api/user/<id>/forgot_password` does not indicate that a resource lives behind it, so it should not be part of a RESTful API.

**Comment by grulg** [comment]
I'm not a whizz in RESTful ways, but I motivated this with [this definition from SO](http://stackoverflow.com/questions/3077229/restful-password-reset).

I believe it would make the framework a lot more flexible. Also, it would be nice if you didn't have to create separate blueprints for this kind of stuff.

But of course, if you feel that it's out of scope, maybe it is. To my own surprise, I haven't seen any other requests for this.

**Comment by jfinkels** [comment]
I believe this is out of scope for Flask-Restless. You should be able to make your own route for `/api/user/:id/password`, but it is certainly not a RESTful endpoint, and hence it is not appropriate for Flask-Restful. I'm going to close this as a "won't fix", but if anyone has a convincing argument for this sort of endpoint, please do contribute or open a new issue (with a convincing test case).

**Comment by laranicolas** [comment]
@grulg +1, I think too it would make the extension more flexible. It is an opportunnity to take the challenge and propose a contribution.

It's a shame not to have custom urls (actions that don't fit into the world of CRUD operations).

**Comment by grulg** [comment]
@laranicolas Hm... Maybe I'll get around to forking and see if I can conjure up some kind of proposal, good idea. Sounds like a good weekend hack or two. ^^

**Comment by laranicolas** [comment]
ROCK!
