### ISSUE TITLE
Custom serialization when make query

### ISSUE THREAD

**Issue by LiveStalker** [jfinkels/flask-restless#413]
Hello!
Custom serialization not working when I make query.
Example:
/url/model?q=... does not apply custom serialization
/url/model/id custom serialization work fine

    def get(self, instid, relationname, relationinstid):
     ...
        if instid is None:
            return self._search() //it is return default serialized objects
    ...
       if relationname is None:
            result = self.serialize(instance)

**Comment by abridgett** [comment]
This also appears to affect when all instances are fetched (e.g. /url/model)

**Comment by abridgett** [comment]
No idea if it's _correct_ but if you replace the to_dict call in views.py's _paginated function with a call to self.serialize fixes the issue for me:
```
       objects = [self.serialize(x)
                   for x in instances[start:end]]
````

**Comment by jfinkels** [comment]
This should be fixed in the development version.
