### ISSUE TITLE
Getting attribute by ID is empty even if object exists on table

### ISSUE THREAD

**Issue by scooterman** [jfinkels/flask-restless#414]
This bug appears on 0.16.0+ (inclusive)

```python
class Role(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode(64), unique=True)
    role_type = db.Column(db.Enum('ADMIN', 'USER', 'EXTENSION'), nullable=False, default='USER')
    allowed_extensions = db.relationship('RoleExtension', cascade='all, delete, delete-orphan')
    permissions = db.Column(db.Integer, default=0)

class RoleExtension(db.Model):
    pattern = db.Column(db.String(80), index=True, primary_key=True)
    role_id = db.Column(db.Integer, db.ForeignKey('role.id'), primary_key=True)
    role = db.relationship('Role', single_parent=True)
```

calling <ur>/api/role/2 on versions prior 0.16:

[base.py:912 -     _execute_context() ] SELECT role.id AS role_id, role.name AS role_name, role.role_type AS role_role_type, role.permissions AS role_permissions
FROM role
WHERE role.id = %s
 LIMIT %s
[base.py:915 -     _execute_context() ] ('2', 1)

on versions after 0.16:

[base.py:912 -     _execute_context() ] SELECT role.id AS role_id, role.name AS role_name, role.role_type AS role_role_type, role.permissions AS role_permissions
FROM role
WHERE role.id = 1
 LIMIT %s
[base.py:915 -     _execute_context() ] (1,)

Seems that flask-restless is completely ignoring the id from the request.

**Comment by jfinkels** [comment]
Can you please provide a minimum working example, or even better, a pull request with a unit test (similar to the ones in `tests/test_views.py`) that demonstrates the issue?

**Comment by scooterman** [comment]
@jfinkels, I've did some debugging here and the problem was that the on newer versions the preprocessor result can change the object id based on it's return value. One preprocessor of mine was returning True, and hence always converting the id to 1.
