### ISSUE TITLE
Wildcard search does not match beginning of string

### ISSUE THREAD

**Issue by mozey** [jfinkels/flask-restless#415]
Consider the following SQL query, it gives me back one database row:

    select * from task where description like '%Something%';

I would expect the following query to produce the same, but I get zero results:

    api/task?q={"filters":[{"name":"description","op":"like","val":"%Something%"}]}

When I search for "Something%", I do get back the same row as the SQL query.

**Comment by jfinkels** [comment]
I think this is because you need to [URL encode][1] your query parameters. This should be noted in the documentation.

[1]: https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_the_percent_character

**Comment by jfinkels** [comment]
This explains #331 also.

**Comment by jfinkels** [comment]
Let me know if that works for you so I can close this issue.

**Comment by mozey** [comment]
Ah! Was pasting the queries into the address bar, I thought the browser would do the encoding automatically. Odd that "Something%" does work without explicitly encoding.
