### ISSUE TITLE
Using multiple APIManager instances no longer works

### ISSUE THREAD

**Issue by da4089** [jfinkels/flask-restless#416]
In my code, I use two APIManagers, as way of running a standard pre-processor for one set of APIs, but not for another:

```
manager = APIManager(
    flask_app,
    flask_sqlalchemy_db=db,
    session=session,
    preprocessors=dict(GET_MANY=[check_access],
                       GET_SINGLE=[check_access],
                       POST=[check_access],
                       PATCH=[check_access],
                       DELETE=[check_access]))

insecure_manager = APIManager(
    flask_app,
    flask_sqlalchemy_db=db,
    session=session)
```

This works nicely in 0.15, but no longer works in 0.17.

Not sure if this was intentional in the recent refactoring: if it was, is there a better way that I should do something like this?

**Comment by freeznet** [comment]
facing the same problem, just downgrade to 0.14

**Comment by jfinkels** [comment]
This should be fixed in the development version.
