### ISSUE TITLE
Flask throws ERROR<500> if Accept headers are badly formatted.

### ISSUE THREAD

**Issue by drmclean** [jfinkels/flask-restless#419]
recently had a problem where Flask would return Error <500> to POST requests from a certain source. 
I eventually tracked down the error as the fact that the source was added an Accept Header that was badly formatted. 

The header would look like this:

    -H 'Accept: application/json; text/javascript'

Changing to 

    -H 'Accept: application/json, text/javascript'
or
    -H 'Accept: application/json'
or 
    -H 'Accept: text/javascript' 

prevents the error. 

It would be nice if Flask returned a helpful message such as "incorrect format of Accept header" etc. etc.
rather than Error<500>

**Comment by jfinkels** [comment]
This should be fixed; the server now responds with "406 Not acceptable".
