### ISSUE TITLE
Custom serialization on root path

### ISSUE THREAD

**Issue by Amnesthesia** [jfinkels/flask-restless#422]
I've added custom serializers using the `serializer=` keyword in create_api, and it works fine for single resources. How do I make this work for calls that return many objects?

`/api/myresources/1` works fine
`/api/myresources` does not trigger any serializer at all

**Comment by abridgett** [comment]
This is the same issue as #413 BTW - I've put a possible workaround there FYI

**Comment by Amnesthesia** [comment]
That's great but I don't want to have to change the source of a dependency in my project as I would have to do this on any machine I install on :( Is there a good way to override it?

**Comment by abridgett** [comment]
As you say, it's a dependency, so either the fix (if it's correct for _everyone_) needs including upstream, or you'll have to patch it locally (or setup your own python package repo and fix it there).

**Comment by jfinkels** [comment]
This should be fixed in the development version.
