### ISSUE TITLE
Is there any way to make GET request using a querystring and POST request with post params

### ISSUE THREAD

**Issue by hussaintamboli** [jfinkels/flask-restless#427]
I have went through the HTTP methods specified here http://flask-restless.readthedocs.org/en/latest/customizing.html

For a GET request I didn't see any way of making below request

    http://127.0.0.1:5000/api/user?name=hussain&username=hussain_tamboli

With a `querystring` (sic)

The way of using `q=<json>` seem a little tedious during the integration.

**Comment by jfinkels** [comment]
Currently, you must use the `filter[objects]=[...]` syntax to filter requests, as suggested by the JSON API specification. It is tedious, but it is part of a tradeoff between generality and simplicity.
