### ISSUE TITLE
Errors when ordering by multiple fields of a model in SQLAlchemy 1.0.2

### ISSUE THREAD

**Issue by elvis-macak** [jfinkels/flask-restless#432]
when using sqlalchemy 1.0.2 as described in requirements, it cause lots of bug.

the following code runs ok in sqlalchemy 0.9.8, but error in 1.0.2
<pre>
session.query(Computer).join(Person).order_by('person.age').order_by('person.name').count()
session.query(Computer).join(Person).order_by('person.age').join(Person).order_by('person.name').count()
</pre>

as my commit https://github.com/jfinkels/flask-restless/commit/9b06b9573c8742d448442787421fd36e126f307c, i check it before join to fix the multiple join error, but meet other bugs(also caused by the sqlalchemy 1.0.2).

finally, i rollback the sqlalchemy to 0.9.8, but it's still an import bug.

**Comment by jonafato** [comment]
@elvis-macak There were quite a few [bug fixes](http://docs.sqlalchemy.org/en/latest/changelog/changelog_10.html#change-1.0.5) made after SQLAlchemy 1.0.0 was released. Do you still have the same issues with the current stable version (1.0.5)?

**Comment by jfinkels** [comment]
Yes, please check a more recent version of SQLAlchemy (i.e. later than 1.0.2). If your problems are solved, then I will increase the minimum version requirement of SQLAlchemy.

**Comment by jfinkels** [comment]
This should be fixed by commit 64a57112e8e5a8e59e46400776d8b1dcc07c4264.
