### ISSUE TITLE
order_by together with results_per_page will only order the visible page

### ISSUE THREAD

**Issue by jwanglof** [jfinkels/flask-restless#434]
I have a fairly large database that I want to paginate and also be able to order by some values. I've noticed that when using results_per_page (in my case 20) the order_by will only affect the page that is viewed. Is it designed like this?

I would like that the order_by doesn't care about results_per_page but orders the query, and then just send back the amount set on results_per_page.

**Comment by jfinkels** [comment]
This should be fixed in the development version.
