### ISSUE TITLE
Filter on relationships: AttributeError: 'unicode' object has no attribute '_sa_instance_state'

### ISSUE THREAD

**Issue by alibozorgkhan** [jfinkels/flask-restless#437]
I'm trying to call an API using the following parameters:

```
{"filters":[{"name":"job__company_id","op":"eq","value":"123"}]}
```

In this case, when I get to `_create_operation`, I have the following variables:

```
model: jobModel
fieldname: 'company_id'
operator: 'eq'
argument: '123'
relation: 'job'
```

On https://github.com/jfinkels/flask-restless/blob/master/flask_restless/search.py#L400, field will be `jobModel.job` as relationship is not `None`. Then on https://github.com/jfinkels/flask-restless/blob/master/flask_restless/search.py#L410, `jobModel.job` and `123` are passed to opfunc which doesn't seem right. Because `jobModel.job.company_id` needs to be `123` not `jobModel.job`.

On the other hand, I get `AttributeError: 'unicode' object has no attribute '_sa_instance_state'` error from `opfunc` call. Is there something I'm missing here or it is a bug?

**Comment by jfinkels** [comment]
In the development version of Flask-Restless we no longer uses the double underscore. Instead use `has` and `any`: http://flask-restless.readthedocs.org/en/latest/fetching.html#using-has-and-any

Unfortunately, I won't be backporting this fix to version 0.17.0, I apologize for the inconvenience.
