### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by EvanSmithMSMD** [jfinkels/flask-restless#442]
Hello,

Currently I am using 
        apimanager.create_api( ...   results_per_page=500, ...)
To control my pagination.

How can my users of this URL request all the pages via my service.  Basically ignoring results_per_page?

Thanks,
Evan

**Comment by EvanSmithMSMD** [comment]
Our consumers of this service (a UI) wishes to get all the pages in some cases.  How would they do this?  Clearly iterating over the pages is possible, but that generates to many requests over the wire and is slow (I would think).  How does one get a bulk read and pagination.  Or is it one or the other?

**Comment by drmclean** [comment]
question : do you actually get 500 results per page when you specify this? Mine maxes out at 100 no matter what I set the limit as...

**Comment by EvanSmithMSMD** [comment]
I don't think you get exactly 500.  I tend set pagination to -1, so that 
the client uses the limit/offset to control what they request.  
Otherwise the client is always making requests and is unable to control 
what they want.

Evan

David McLean wrote:
>
> question : do you actually get 500 results per page when you specify 
> this? Mine maxes out at 100 no matter what I set the limit as...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jfinkels/flask-restless/issues/442#issuecomment-113114083>.
>

-- 


Evan C. Smith, MS, MD
Evan.Smith.MS.MD@gmail.com
Cell: 781-879-8736

**Comment by drmclean** [comment]
false alarm, apparently you have to set results_per_page AND max_results_per_page. Not entirely sure why it's arranged like that but hey ho.

**Comment by jfinkels** [comment]
One keyword argument sets the default page size, but clients can override that, and one argument sets the maximum possible page size that clients can request, and clients cannot override that. For more information, see http://flask-restless.readthedocs.org/en/latest/fetching.html#pagination and `page_size` under http://flask-restless.readthedocs.org/en/latest/api.html#flask.ext.restless.APIManager.create_api.

To disable pagination entirely, set both arguments to zero.
