### ISSUE TITLE
Flask restless - A search filter for a relationship.property != val in case of one-to-many relationship

### ISSUE THREAD

**Issue by hussaintamboli** [jfinkels/flask-restless#447]
Hello,

Can anyone help me out on this one -- http://stackoverflow.com/questions/30868718/flask-restless-a-search-filter-for-a-relationship-property-val-in-case-of-o

**Comment by Meph-** [comment]
I wrote answer there, try it:
http://stackoverflow.com/a/30931183/2107985

**Comment by hussaintamboli** [comment]
It gives an error - 

    Can't compare a collection to an object or collection; use contains() to test for membership. 

with response - 

    { 
       "message": "Unable to construct query" 
    }

**Comment by jfinkels** [comment]
This should be fixed in the development version. If not, open a new issue with a *minimal* working example of the problem.
