### ISSUE TITLE
Session should be rolled back on SQLAlchemyError

### ISSUE THREAD

**Issue by hussaintamboli** [jfinkels/flask-restless#449]
Yesterday, I came across a really painful issue.

I use flask-restless and SQLAlchemy for my API. I got **Internal server error** due to `OperationalError` exception in one of my APIs. It was because one of the required column was not passed to the POST request. After that, for all the subsequent requests I started getting another Internal server error due to `InvalidRequestError` exception.

    InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback() .... 

After a long search I found that a `rollback()` [needs to be issued](http://docs.sqlalchemy.org/en/rel_0_8/faq.html#this-session-s-transaction-has-been-rolled-back-due-to-a-previous-exception-during-flush-or-similar) when an error occurs in `commit()`. But in this case the commit and rollback is not in my hands but restful's. 

So I started looking where and when the rollback is being issued in restless and found [these lines](https://github.com/jfinkels/flask-restless/blob/master/flask_restless/views.py#L190-L192) in `views.py`

    190 # TODO should `sqlalchemy.exc.InvalidRequestError`s also be caught?
    191 except (DataError, IntegrityError, ProgrammingError) as exception:
    192   session.rollback()

Note that `OperationalError` is not handled as a rollback case.

So as a FIX to my issue I modified the `views.py` and put `OperationalError` in it. Then I thought, to be on safer side why not issue the rollback on `SQLAlchemyError` (**SQLAlchemy base exception class**)

I have created a pull request with my fix. 

Please let me know your thoughts on this

**Comment by hussaintamboli** [comment]
Hi, 

Could you please accept my merge request. Because I really want to install flask_restless using pip. And I don't wanna put flask_restless with my fix inside version control.

Without this fix, the randomness issue persists.

**Comment by jwg4** [comment]
@hussaintamboli  Why did you close the issue if your code has not been merged? You should re-open the issue.

**Comment by jfinkels** [comment]
This should be fixed by 56c82616df2c72ff72d3be4a3e7cb9f74bec409b.

**Comment by hussaintamboli** [comment]
Great.

Actually the pull request that I had sent before (4bed33f) has the same fix.

Thanks.
