### ISSUE TITLE
How to call session.remove() "on request end" for SQLAlchemy

### ISSUE THREAD

**Issue by hussaintamboli** [jfinkels/flask-restless#451]
Hello,

I use `sqlalchemy` and `flask-restless` for creating an API. I guess the transactions are not properly being committed because I just noticed that.

- Db changes taking some time even though I am doing commit()
- The num_results for a GET request are sometimes random. e.g. I have 10 rows in my country table. When I hit /country API, I get 10, 9, 10, 8 results. Something's wrong here.

Previously, I was using `flask-sqlalchemy` and I didn't have these issues.

While reading sqlalchemy documentation, I found this post called [using thread local scope with web applications](http://docs.sqlalchemy.org/en/rel_1_0/orm/contextual.html#using-thread-local-scope-with-web-applications). It says and I quote

> the process of integrating the Session with the web application has exactly two requirements:
> 1. Create a single scoped_session registry when the web application first starts, ensuring that this object is accessible by the rest of the application.
> 2. Ensure that scoped_session.remove() is called when the web request ends, usually by integrating with the web framework’s event system to establish an “on request end” event.

I guess `flask-sqlalchemy` was doing this somehow. How do I do this with my existing setup

Snippet from existing setup:

    # ... snip of model.py ...

    Model = declarative_base()
    engine = create_engine('mysql://root:root123@localhost/mydb?charset=utf8', convert_unicode=True, echo=True)
    Session = orm.sessionmaker(autocommit=False, autoflush=True, bind=engine)
    mysession = orm.scoped_session(Session)
    Model.metadata.bind = engine

    class Country(Model):

        __tablename__ = 'country'

        id = Column(Integer, primary_key=True)
        name = Column(String(150), nullable=False, unique=True)
        created_on = Column(DateTime, default=_get_date_time)
        modified_on = Column(TIMESTAMP, onupdate=_get_date_time, nullable=False,      server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))
        is_deleted = Column(mysql.TINYINT, nullable=False, default=0, server_default=text("0")

    # .... snip of api.y ....
    # API is created using flask-restless and sqlalchemy
    manager = flask.ext.restless.APIManager(app, session=mysession)
    manager.create_api(Country, methods=['GET', 'POST'], url_prefix='/api/v1')

Please help me out.

**Comment by ilyastam** [comment]
Here is how flask-sqlalchemy does it:
https://github.com/mitsuhiko/flask-sqlalchemy/blob/master/flask_sqlalchemy/__init__.py#L816

something like this should work:
@app.after_request
def remove_session(response):
  mysession.remove()

**Comment by hussaintamboli** [comment]
Yes. I had figured that out. I feel sorry, I didn't put an update on this issue :(

I am kind of doing the same thing already

    @app.teardown_appcontext
    def shutdown_session(exception=None):
        # Sessions in SQLAlchemy should scoped, meaning that each request handler creates and destroys its own session.
        # DETAILS:
        # The process of integrating the SQLAlchemy Session with the web application has exactly two requirements:
        # 1. Create a single scoped_session registry when the web application first starts,
        # ensuring that this object is accessible by the rest of the application.
        # 2. Ensure that scoped_session.remove() is called when the web request ends,
        # usually by integrating with the web framework's event system to establish an "on request end" event.
        # Refer:
        # http://docs.sqlalchemy.org/en/rel_1_0/orm/contextual.html#using-thread-local-scope-with-web-applications
        # http://stackoverflow.com/questions/19395697/sqlalchemy-session-not-getting-removed-properly-in-flask-testing
        print("closing session on request end")
        session.remove()
