### ISSUE TITLE
Missing type check on "toremove" in _remove_from_relation in views.py

### ISSUE THREAD

**Issue by dan-compton** [jfinkels/flask-restless#455]
It's the same type check that goes on _add_to_relation which takes care of the case in which add (toremove in this case) is a single dictionary rather than a list.  Simply wraps the dict in a list.

https://github.com/jfinkels/flask-restless/pull/454

**Comment by jfinkels** [comment]
I have updated the code to follow the JSON API protocol, so this is no longer an issue.
