### ISSUE TITLE
Exclude relations in collections

### ISSUE THREAD

**Issue by samtux** [jfinkels/flask-restless#456]
Hello, I have the following response of a particular element:
```
/api/formularios/1108
```
```json
{
  "codigoformulario": "126PM04-PR82-F-A1",
  "grupo": {
    "idgrupotrabajo": 540544,
    "nombre": "AGUAS SUBT"
  },
  "idformulario": 1108,
  "idgrupotrabajo": 540544,
  "nombreformulario": "Identificacion Terceros"
}
```
However when I deploy the relationship of "preguntas" delivered the collection of "respuesta" that is excluded in the "Preguntas" API configuration:
```
/api/formularios/1108/preguntas
```
```json
{
  "num_results": 59,
  "objects": [
    {
      "formulario": {
        "codigoformulario": "126PM04-PR82-F-A1",
        "idformulario": 1108,
        "idgrupotrabajo": 540544,
        "nombreformulario": "Identificacion Terceros"
      },
      "idformulario": 1108,
      "idpregunta": 80135,
      "pregunta": "Correo Electronico",
      "respuestas": [ {...}, {...}]
....
```
Here the API configuration of "Preguntas" excluding the relationship "respuestas":
```Python
preguntas_api = manager.create_api_blueprint(Pregunta, methods=['GET'], collection_name='preguntas', results_per_page=10, exclude_columns=["respuestas"])
```
How I can exclude relations with two levels deep collections?, such as /api/formularios/1108/preguntas.

Thanks.

**Comment by fattarsi** [comment]
I was also having the same issue. I put in a pull request to address it, for consideration.
https://github.com/jfinkels/flask-restless/pull/459

**Comment by jfinkels** [comment]
Hi!

I have updated the code to follow the JSON API protocol, so I will not fix this issue.
