### ISSUE TITLE
PATCH returning 404 - but still makes the change

### ISSUE THREAD

**Issue by erikwilliamson** [jfinkels/flask-restless#458]
Hi,

I'm using Flask-Restless 0.16.0 - this only happens when using the primary_key='some_field' parameter in the create_api() method. Always returns a 404 even thought the change gets made. I can post sample code but it's pretty easy to replicate.

No issue when patching a field other than that which is named in primary_key.

I can work around the issue by adding the following around views.py line 1521:

```python
if patchmany:
    # ...
else:
    if self.primary_key in data:
        instid = data[self.primary_key]
    result = self._instid_to_dict(instid)
    # ...
```

**Comment by datashaman** [comment]
+1 Same problem

**Comment by jfinkels** [comment]
I have substantially rewritten the code, so if this is still an issue, please open a new issue and provide a test case that causes the unexpected behavior.
