### ISSUE TITLE
custom serializer/deserializer

### ISSUE THREAD

**Issue by jklapuch** [jfinkels/flask-restless#460]
Why not custom serializer/deserializer used for GET_MANY requests? Response always contains all attributes of the model.

**Comment by spight** [comment]
+1. It' not clear in the documentation that the serializer option doesn't apply to GET_MANY requests, and the default to_dict function has a bad habit of exposing sensitive information, such as users' email addresses if you create an API for a model that has an owner. This problem should get more attention.

**Comment by augustjd** [comment]
+1 Without @spight, I would not have known that serializer doesn't apply to GET_MANY requests. I don't see any legitimate reason why that should be the case; at the very least, the documentation should be updated.

**Comment by jfinkels** [comment]
This should be fixed in the development version.
