### ISSUE TITLE
db.Interval claims to be supported but isn't

### ISSUE THREAD

**Issue by drmclean** [jfinkels/flask-restless#463]
using db.Interval to specify a time interval is in the docs here: http://flask-restless.readthedocs.org/en/latest/requestformat.html

however when defining a table with db.Interval and representing the interval as an integer number of seconds flask-restless throws a JSON error when attempting to return this value. 

That is: I can successfully POST an Interval into the database but Flask throws 
TypeError: datetime.timedelta(1, 53600) is not JSON serializable when it attempts to construct the response to the post.

**Comment by drmclean** [comment]
for anyone waiting, I think this successfully fixes the bug  for now

import datetime as dt

def duration_fix(result=None, **kw):
    try:
        if isinstance(result[<column-name>], dt.timedelta):
            result[<column-name>] = result[<column-name>].seconds
    except:
        <your own error handling>

**Comment by jfinkels** [comment]
This should be fixed now, see https://github.com/jfinkels/flask-restless/blob/master/flask_restless/serialization.py#L384.
