### ISSUE TITLE
How to bulk update using patch ?

### ISSUE THREAD

**Issue by mayuroks** [jfinkels/flask-restless#467]
Hi I am **looking for bulk patch example.**
1) I am using flask-restless
2) in create_api, I have **done allow_patch_many=True**
3) methods=['GET', 'POST', 'DELETE', 'PATCH']

I have a simple **model**
```python
class Job(db.Model):
    __tablename__ = "jobs"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.Text)
    interval = db.Column(db.Integer)
    func = db.Column(db.LargeBinary)
    next_runtime = db.Column(db.DateTime)
```

But when I **try to send a patch request like below, I get 500 error**
```python
from request import patch
import json

data = [{'id':1, 'name': 'wow'}, {'id':2, 'name': 'hey'}]
res = patch(url='http://127.0.0.1:5000/api/jobs', data=json.dumps(data))
res.status_code  => 500
```

**I have multiple objects of same model.**
I just want an example of bulk updating those objects at once.

**Comment by Meph-** [comment]
I think you should use a filter query for batch updating and data use only for a new value of attribute.

see http://flask-restless.readthedocs.org/en/latest/requestformat.html#put--api-person

**Comment by mayuroks** [comment]
I looked at the example.
```python
PATCH /api/person HTTP/1.1
Host: example.com

{
  "age": 1,
  "q": {"filters": [{"name": "name", "op": "like", "val": "%y%"}]}
}
```

looks like all the fields matching the filters will be updated with **age: 1** value.
**BUT** my use case is different. I want to update same fields with different values for different objects.

**Comment by Meph-** [comment]
I thought so , but I am not sure whether this is possible.
Try to define some preprocessor for this, but you need to figure how disable standard processing of flask-restless and return correct data ({"num_modified": 3}).
Or set up own endpoint for this purpose, like:

     @app.route("/api/jobs/patch_many", methods=['PATCH'])


    def patch_many_preprocessor(data=None, **kwargs):
 with next parts:
1)  which will determine patch single / many. And then use db.model for get

**Comment by Meph-** [comment]
I thought so , but I am not sure whether this is possible.
Try to define some preprocessor for this, but you need to figure how disable standard processing of flask-restless and return correct data ({"num_modified": 3}).
Or set up own endpoint for this purpose, like:

    @app.route("/api/jobs/patch_many", methods=['PATCH'])
    def jobs_patch_many():
        # add some error handling.
        if u'application/json' in request.headers['Content-type']:
             data = request.get_json()
             for job in data:
                 record = Job.query.get(job.id)  # or get all items for patch
                 # now modified record attributes
                 ...
            db.session.commit()
        
            # if no errors:
            return jsonify({"num_modified": len(data)}
        else:
            # .....

**Comment by jfinkels** [comment]
Hi,

I have updated the code to follow the JSON API protocol, so I will not be fixing this issue. Bulk updates should be handled by the JSON API Bulk extension (see issue #477).
