### ISSUE TITLE
LIKE Filter doesn't work properly for particular values like %ac% and %de%

### ISSUE THREAD

**Issue by hussaintamboli** [jfinkels/flask-restless#469]
I have rows in my table having account as title. But when I use below filter, It doesn't search it

    {
        "filters": [
            {"name":"title","op":"like","val":"%account%"}
        ]
    }

The value that is searched in the SELECT query is `'\xef\xbf\xbdcount%'`

And when I search some other string using the same filter

    {
        "filters": [
            {"name":"title","op":"like","val":"%customer%"}
        ]
    }
I see the correct value being searched. viz `'customer'`

It also doesn't work for %designer%.

I don't understand what is going on.

**Comment by jfinkels** [comment]
Make sure the query parameters are percent-encoded in your URLs when the client makes the request.

**Comment by hussaintamboli** [comment]
I don't know what you mean by that? Do you mean url-encoded? 

But you see it works for "%customer%" but not for "%desinger%" and "%account%". Isn't there something wrong?
