### ISSUE TITLE
Multipatching is not working on queries that are returned by search criteria

### ISSUE THREAD

**Issue by pikamar** [jfinkels/flask-restless#472]
My data in database:
{
    "num_results": 7,
    "objects": [
        {
            "birth_date": "1990-01-22",
            "id": 3,
            "name": "Sasa"
        },
        {
            "birth_date": "1990-01-22",
            "id": 4,
            "name": "Peter 2"
        },
        {
            "birth_date": "1990-01-22",
            "id": 5,
            "name": "Dacia"
        },
        {
            "birth_date": "1990-01-22",
            "id": 6,
            "name": "Roma"
        },
        {
            "birth_date": "1990-01-22",
            "id": 7,
            "name": "Lenta"
        },
        {
            "birth_date": "1990-01-22",
            "id": 8,
            "name": "Peter 101"
        },
        {
            "birth_date": "1990-01-22",
            "id": 9,
            "name": "Ķērpis"
        }
    ],
    "page": 1,
    "total_pages": 1
}

I wanted to update(PUT) birth_date value to "22/01/1990" for name that starts with P%, but as a result update was done for all 7 records. Expected result was 2 updated entries.

From flask documentation:
https://flask-restless.readthedocs.org/en/latest/customizing.html#allowmany
"... If search parameters are provided via the q query parameter as described in Making search queries, only those instances matching the search will be patched. ..."

Screenshot from Postman:
![image](https://cloud.githubusercontent.com/assets/14360648/12334932/4b8e41ba-bb05-11e5-85d1-3980c4e464f3.png)

Did not tried for DELETE.

**Comment by jfinkels** [comment]
I have rewritten the project to use the JSON API protocol, so I will not be fixing this. Making updates to multiple resources should be handled by the JSON API Bulk extension (see issue #477).
