### ISSUE TITLE
Include license files in pypi tarballs

### ISSUE THREAD

**Issue by AdamWill** [jfinkels/flask-restless#474]
Hi, there. The two license files - LICENSE.AGPL and LICENSE.BSD - are not included in the pypi tarballs for flask-restless. Per the Fedora licensing guidelines:

https://fedoraproject.org/wiki/Packaging:LicensingGuidelines

and similar guidelines for other distributions (e.g. Debian), it is a really good idea to include the license with the software. This is particularly the case for the BSD license, as one of the conditions of the BSD license is that it be included with distributions of the software - "Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer." - so it's rather difficult when the canonical distribution of the source does *not* contain the license.

If they could be included in the tarballs it'd be a help to distributions and other downstreams. Thanks!

**Comment by jfinkels** [comment]
This should be fixed by 5e166737b3f20674593306ed22bc29b9d0774fd4.
