### ISSUE TITLE
Headers appear twice in response to the client

### ISSUE THREAD

**Issue by jfinkels** [jfinkels/flask-restless#479]
Some headers seem to appear twice when receiving a response from Flask-Restless.

**Comment by hoest** [comment]
Have the same issue:

Flask==0.10.1
Flask-Restless==0.17.0
Flask-SQLAlchemy==2.1
Werkzeug==0.11.4

When creating the same app as mentioned in https://flask-restless.readthedocs.org/en/latest/quickstart.html I get incorrect response headers (Chrome):

![image](https://cloud.githubusercontent.com/assets/606546/13300293/bc7087ee-db3f-11e5-8436-62effd59685c.png)

Double 'Content-Type' and double 'Link' headers.

**Comment by hoest** [comment]
@jfinkels Is this hard to fix?

**Comment by jfinkels** [comment]
I'm not sure! It will just take some poking around to see where the headers
are being set on the response object. I would start by looking at the
`jsonpify()` function.

**Comment by hoest** [comment]
When I do a JSONP with callback request param, I get these headers:

![image](https://cloud.githubusercontent.com/assets/606546/13300759/e1901880-db41-11e5-8c24-ff2ffbb29289.png)

**Comment by hoest** [comment]
The problem does not occur in Safari or Firefox...

**Comment by jfinkels** [comment]
I have diagnosed this problem and it seems to be due to the fact that the view methods in Flask-Restless return a dictionary (or possibly a dictionary, headers, and/or status code), that dictionary is provided to our `jsonpify()` function, and the response object created there is provided to `mimerender`. The problem is that we create a response object with, for example, a `Content-Type` header, in `jsonpify`, but the `mimerender` code takes the response object returned by `jsonpify` and adds to the headers those headers that were returned by the view method.

More briefly, mimerender adds the headers returned by the view method on top of the headers created by the jsonpify function. So maybe it's time for us to ditch mimerender, since we are not really using it for much of its intended purpose.

**Comment by jfinkels** [comment]
Fixed by pull request #602.
