### ISSUE TITLE
documentation versioning

### ISSUE THREAD

**Issue by deanmalmgren** [jfinkels/flask-restless#485]
I've really been enjoying my first use of Flask-Restless, but I ran into [a problem](http://stackoverflow.com/questions/35331040/unable-to-trigger-flask-restless-postprocessor) trying to implement a `postprocessor` using Flask-Restless 0.17.0. It turns out that, in my googling of "flask restless postprocessor", I landed on the `latest` release of the Flask-Restless documentation, which appears to be based on a pre-release version of the docs and was not what I installed with `pip install Flask-Restless`. It might be better to configure readthedocs to have the `stable` release be the default documentation version when navigating to http://flask-restless.readthedocs.org/

It would also be helpful to have all Flask-Restless versions available.

I'm not sure if this has something to do with the [github <-> readthedocs web hooks](http://read-the-docs.readthedocs.org/en/latest/webhooks.html) or configuration on readthedocs itself, but I thought I'd bring this to your attention so others can more easily use this.

**Comment by jfinkels** [comment]
You are 100% right, I just didn't know how to do this. I'll figure it out as soon as possible.

**Comment by jfinkels** [comment]
This can be configured in the "admin" page for the Flask-Restless project on readthedocs. I have made the necessary changes so that the "stable" version is the default version. Please check it out and let me know if there are any more issues.

**Comment by deanmalmgren** [comment]
Thanks; [I really appreciate it](https://twitter.com/deanmalmgren/status/698102408795148288)!

**Comment by jfinkels** [comment]
No problem, this was an easy one!
