### ISSUE TITLE
Best way to select 'distinct' values from a model field

### ISSUE THREAD

**Issue by roemhildtg** [jfinkels/flask-restless#495]
How can I create custom function on a sqlalchemy model and return a set of values to flask restless so that a GET request can access that set of values in a JSON response?

Ultimitely what I would like to do is have a custom function on a model, that returns distinct values for a field argument.

```
class MyModel(db.Model):
    #...model fields
    def get_unique_values(self, fieldname):
        #returns an array of unique values for a given field
        #['val1', 'val2' ] 
        return db.session.query(getattr(self, field)).distinct().all()
```

Has anyone accomplished something like this with flask-restless?

**Comment by jfinkels** [comment]
You might try the `additional_attributes` keyword argument to `APIManager.create_api`, which appears in the development version (see https://flask-restless.readthedocs.org/en/latest/api.html#flask.ext.restless.APIManager.create_api). If the attribute is callable, it will be called by the default serialization function in Flask-Restless (see https://github.com/jfinkels/flask-restless/blob/master/flask_restless/serialization.py#L522). In this way you can have your response object include an attribute `unique_values` which will have the result of calling the method `my_instance.unique_values()`. Unfortunately, this technique doesn't allow you to provide any arguments to the callable attribute.

Other techniques may be to use a postprocessor (http://flask-restless.readthedocs.org/en/latest/customizing.html#custom-queries).

**Comment by roemhildtg** [comment]
Okay thanks for the quick reply! I'll give that a shot shortly.

**Comment by roemhildtg** [comment]
I'm having trouble installing the development version. When I install with pip:

`pip install git+https://github.com/jfinkels/flask-restless.git`

It installs correctly but I now have an error, `ImportError: No module named views`. from flask_restless\manager.py line 38.

**Comment by jfinkels** [comment]
See https://packaging.python.org/en/latest/installing/#installing-from-vcs or https://pip.pypa.io/en/latest/reference/pip_install/#git.

**Comment by roemhildtg** [comment]
Oops, my bad. I was missing the -e and the #egg=flask-restless
