### ISSUE TITLE
Flask Restless + Angular - $http PUT - 400 Bad Request

### ISSUE THREAD

**Issue by fergvick** [jfinkels/flask-restless#505]
I am getting a 400 Bad Request when trying to update the database with a PUT request through Angular's $http method (GET request returns without issues). The server is not logging an error. 
Postman returns;
```
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>CSRF token missing or incorrect.</p>
```
How does Flask-Restless handle CSRF tokens and ultimately how can I overcome this problem (I have checked that the information being submitted doesn't go out of the range of the database model).

Thanks

**Comment by jfinkels** [comment]
This is a duplicate of issue #421, I will post a response there.
