### ISSUE TITLE
Adding a pre-commit processor?

### ISSUE THREAD

**Issue by elektito** [jfinkels/flask-restless#508]
I believe there is a case to be made for a adding "pre-commit processors"; that is, one or more callbacks which are called after insertion to/deletion from the database but before the transaction is actually committed. 

Here's the use case I have in mind. An object is posted. We insert it into database so that an `id` is assigned to it and then send it on to a another application (or database), one that needs the `id` pre-assigned, for verification. This application might signal a verification failure and we might need to rollback the transaction at this point.

We can't do this with the "postprocessors" we have right now because those are called after the transaction is committed. There are two ways to implement this, I believe. One is to call the postprocessors before the transaction is committed, and rollback the transaction if a `ProcessingException` is raised. The other is to add a new category of processors. We might call these `precommitprocessors` or something and they are called just before the transaction is committed and give the user a chance to cancel everything.

I personally suggest the first solution as it seems natural to me that when a `ProcessingException` is raised the user expects everything to be canceled.

If this is something that has chance of being accepted (whether the first solution is chosen or the second), I'm willing to write the patch myself and send a pull request.

**Comment by jfinkels** [comment]
I've been thinking for a while that using signals may make more sense for things like this (including the pre- and postprocessors). How do you feel about using a signal-based implementation for a pre-commit/post-commit hook, using [Blinker][1] for example?

[1]: https://pythonhosted.org/blinker/

**Comment by Rezun** [comment]
I'm also in need of this feature. So, I wrote a simple solution in my fork in 7f44f334dcdf028dcc7c6a7fc0201a9dd3c5897d by simply replacing the commits with flushes and committing after the post processors.

I'd also prefer a more common way to handle such scenarios with signals. But how should they be implemented? Should there be a list of signals in the APIManager class, each representing an action? How would one distinguish between the endpoints? There is no object representing an endpoint which could be used as a signal sender. Except the blueprint may be. But that wouldn't be ideal in my opinion. Or should the sender be just the endpoint name? Or is there an obvious implementation I'm just not seeing?

**Comment by elektito** [comment]
@jfinkels I haven't use Blinker specifically, but since there is [native support][1] for it in Flask, it seems like a good option. The question of committing before or after the post-processors, or adding a new callback, still remains though. I'm personally all for merging @Rezun's commit. After that, all callbacks can be changed to signals at any time.

[1]: http://flask.pocoo.org/docs/0.10/signals/

**Comment by jfinkels** [comment]
For now, I have merged the solution in #511. We can discuss other possibly better solutions later (by opening a new issue). Thanks for the help!
