### ISSUE TITLE
combine filter and function evaluation

### ISSUE THREAD

**Issue by FrankMN** [jfinkels/flask-restless#515]
I want to use filter together with a function evaluation, which is like:
`evaluated = session.query(*processed).filter_by(**filter).one()`
While it seems no such feature yet.

**Comment by jfinkels** [comment]
Is this the same as issue #7, which requests the ability evaluate functions after filtering? Or is this different because you wish to filter after evaluating functions?

**Comment by FrankMN** [comment]
I mean, I want to apply 
`{'name': 'avg', 'field': 'age'}`
only on partial records of a model. e.g., `gender = girl`. I also mean evaluate functions after filtering.

**Comment by jfinkels** [comment]
> I mean, I want to apply 
> `{'name': 'avg', 'field': 'age'}`
> only on partial records of a model. e.g., `gender = girl`. I also mean evaluate functions after filtering.

This is filtering *before* evaluating a function, which is what issue #7 requests.

> I want to use filter together with a function evaluation, which is like:
> `evaluated = session.query(*processed).filter_by(**filter).one()`
> While it seems no such feature yet. 

This is filtering *after* evaluating a function, which is a separate (new) issue. In this issue, let's focus only on this. Can you give an example request and response?

**Comment by jfinkels** [comment]
Okay, it appears that in SQLAlchemy, the code you originally suggested,

    session.query(*functions).filter(*filters)

actually behaves differently from how I expected. It applies the filters to the model *before* the functions are computed. So you are actually requesting filtering *before* function evaluation, which is issue #7. I am closing this as a duplicate.

In any case, I have just uploaded pull request #518 which I think implements this behavior. See, for example, the unit test https://github.com/jfinkels/flask-restless/pull/518/files#diff-75e9a536741cd45c0fd1f0d22942a4d7R136
