### ISSUE TITLE
Is it possible to make a same API to return different columns?

### ISSUE THREAD

**Issue by yhosun** [jfinkels/flask-restless#537]
Hello,

This is a question (or maybe, it could be enhancement) , and please, feel free to let me know if you prefer a question to be posted to a different forum like StackOverflow.

Is there any way to make a same API to return different sets of columns?

For example, in the doc,

```python
class Person(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode, unique=True)
    birth_date = db.Column(db.Date)
    computers = db.relationship('Computer')
```
In a UI page displaying a number of people, I would like to fetch and display only `name` while I want to display all columns / relationship in a UI page showing only a few people.

I can create two sets of APIs with different `include_columns` and `url_prefix`.  But, I was wondering if there is a way to make one set of API handle it like passing a parameter `https://myhost.com/pserson/?q=some_query&view=detail` or `https://myhost.com/pserson/?q=some_query&view=list`.  `view=detail` is to return all columns and `view=list` is to return the `name` column.

Thank you.

**Comment by jfinkels** [comment]
Flask-Restless will support JSON API in version 1.0.0, which allows the client to request "[sparse fieldsets][1]" in a fetched resource. The corresponding section of the Flask-Restless documentation describes mostly how to configure this from the server-side. For version 1.0.0b1, the documentation is here: https://flask-restless.readthedocs.io/en/1.0.0b1/fetching.html#specifying-which-fields-appear-in-responses and for the latest version: https://flask-restless.readthedocs.io/en/latest/sparse.html

In short, you can make requests like this:

```http
GET /person?fields[person]=name HTTP/1.1
```

to get a response like this:

```http
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json

{
  "data": [
    {
      "type": "person",
      "id": "1",
      "attributes": {
        "name": "foo"
      }
    }
  ]
}
```

What you are asking for is basically a "shorthand" query parameter `detail`, for which the server would expand `detail=low` to `fields[person]=name` and `detail=high` to `fields[person]=name,age,height,...`. Is that right?

[1]: http://jsonapi.org/format/#fetching-sparse-fieldsets

**Comment by yhosun** [comment]
Awesome! I did not know that the `fieldset` will be supported from 1.0.0.

It would be nice to have a shorthand parameter feature, so that the client code does not need to list parameters.

By the way, do you have a upgrade guide (document) from 0.17.0 to 1.0.0?  I do not remember the exact error, but last time when I tried to upgrade to 1.0.0b1 with my current code, I got errors.  It could be because a function signature has changed.

Thank you very much for your help!

**Comment by jfinkels** [comment]
I don't currently have a migration guide, see issue #535.

Unfortunately, I think it would be more of a pain that it would be worth. From the JSON API specification:

> The value of the fields parameter MUST be a comma-separated (U+002C COMMA, “,”) list that refers to the name(s) of the fields to be returned.

So I couldn't do something like `fields[person]=lotsofstuff`, where `lotsofstuff` is a shorthand for a list of fields, because that would violate the specification. The only other implementation I can imagine is specifying a "shorthand" query parameter when creating the API, then allowing the client to use that query parameter. That raises issues like "How does the client specify which resource it wants to be detailed, if multiple types of resources are returned in a response?", etc. I'd rather not create a whole new type of query parameter for this use case, since it is already captured by using sparse fieldsets.

**Comment by jfinkels** [comment]
I'm going to mark this as "won't fix", since for now I'm going to require that the client specify the exact fields it wants to see in the response.
