### ISSUE TITLE
How to set the alias for my model columns and methods?

### ISSUE THREAD

**Issue by thrbowl** [jfinkels/flask-restless#550]
Does flask-restless support the feature now?

**Comment by jfinkels** [comment]
Can you give an example of what you are asking about?

**Comment by jfinkels** [comment]
Are you asking for a feature in which a field named `foo` appears in the JSON response document under a different name? Flask-Restless does not support this directly, but you could implement it using [postprocessors][1].

[1]: http://flask-restless.readthedocs.io/en/latest/serialization.html

**Comment by jfinkels** [comment]
Closing due to lack of information.
