### ISSUE TITLE
Select Columns on a GET request

### ISSUE THREAD

**Issue by talatbaig** [jfinkels/flask-restless#551]
Hi,

I wanted to ask if there was any way to select particular columns when making a GET request. 
I know there is an include_columns option but what would be nice is if I could specify particular columns from include_columns in my request and only get those back.

Kind regards
T

**Comment by jfinkels** [comment]
As of version 1.0.0b1, Flask-Restless supports JSON API, which allows the client to specify which fields to include in a response via the `fields` query parameter. For more information, see the "[Sparse Fieldsets][1]" section of the JSON API specification and the [corresponding section of the Flask-Restless documentation][2] for the latest version.

[1]: http://jsonapi.org/format/#fetching-sparse-fieldsets
[2]: https://flask-restless.readthedocs.io/en/latest/sparse.html

**Comment by talatbaig** [comment]
Awesome thanks!
