### ISSUE TITLE
Python 2.6 support

### ISSUE THREAD

**Issue by vrajmohan** [jfinkels/flask-restless#566]
Travis builds are failing with:
```
Downloading SAValidation-0.4.0.tar.gz

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-build-tC6x8w/savalidation/setup.py", line 53, in <module>

        '1.2' if sys.version_info.major == 2 else '1.3.0a1',

    AttributeError: 'tuple' object has no attribute 'major'
```
`sqlalchemy-validation` is tested only with Python 2.7 and higher - https://github.com/blazelibs/sqlalchemy-validation/blob/master/tox.ini#L2.

Also, Python 2.6 has been officially retired - https://www.python.org/download/releases/2.6.9/.

Shouldn't we cease testing with Python 2.6?

**Comment by jfinkels** [comment]
I will remove the (very limited anyway) support for `savalidation` from the code and the tests, since it has always been very troublesome. I must support Python 2.6 in order to be an "Approved Extension" for Flask: http://flask.pocoo.org/docs/0.11/extensiondev/#approved-extensions
