### ISSUE TITLE
init_app doesn't set the app attribute

### ISSUE THREAD

**Issue by stephane** [jfinkels/flask-restless#571]
It seems weird to me `APIManager.init_app` doesn't set the app:

https://github.com/jfinkels/flask-restless/blob/master/flask_restless/manager.py#L325

In my app, I start by registering all the extensions this way:

```
# database doesn't import the app...
from .database import db
db.init_app(app)
```

then I'm able to register all my blueprints but with Flask-Restless I need to call `api_manager.init_app` at the very end (after the calls to `create_api`) to effectively register all the blueprints.

**Comment by jfinkels** [comment]
This is intentional, see the "Note on `init_app`" in *[Flask Extension Development][1]*. That's why we require that you call `manager.create_api()` before calling `manager.init_app()`.

[1]: http://flask.pocoo.org/docs/0.11/extensiondev/#the-extension-code

**Comment by stephane** [comment]
Ah OK!
