### ISSUE TITLE
Upload Flask-Restless-1.0.0b1.tar.gz to pypi.python.org

### ISSUE THREAD

**Issue by daniellawrence** [jfinkels/flask-restless#575]
Hey @jfinkels ,

  Thanks for putting all of this together so far, its been a massive time saver :)

  Can you please upload the JSONAPI branch 1.0.0b1 to https://pypi.python.org/simple/flask-restless/
  This will let me upload this to an internal pypi.

Cheers,

Daniel

**Comment by jfinkels** [comment]
Hi @daniellawrence! The version 1.0.0b1 release seems to be there under the name [Flask_Restless-1.0.0b1-py2.py3-none-any.whl][1]. Not sure why the hyphen has become an underscore here, maybe it has something to do with the new Python wheel format. Anyway, the `.whl` file is actually just a .zip file, in case you need to inspect the contents. Please let me know if that's sufficient for your needs.

[1]: https://pypi.python.org/packages/67/68/fcd45aa1824af2fe34378d564a57808207a5eb0169f642b3a502dfb2e150/Flask_Restless-1.0.0b1-py2.py3-none-any.whl#md5=3fe68a7f52b4a56c7906161aea893503

**Comment by daniellawrence** [comment]
Hello,
   
   The wheel formats should work for everyone, the only problem I have is our internal ftpmaster is only happy with mirroring packages with **--no-binary** option for security reasons. As wheel files can contain compiled files, these uploads are filtered out by the --no-binary option.

   If your able to,  uploading to pypi you can use the **sdist** option should fix the problem.

```
$ python setup.py sdist upload
```
    

```
$ pip install --no-binary :all: --download ./cache --index-url https://pypi.python.org/simple flask-restless==1.0.0b1
Collecting flask-restless==1.0.0b1
  Could not find a version that satisfies the requirement flask-restless==1.0.0b1 (from versions: 0.3.dev0, 0.3, 0.4, 0.5, 0.6, 0.7.0, 0.8.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.17.0)
No matching distribution found for flask-restless==1.0.0b1
```

**Comment by jfinkels** [comment]
Okay, I see. I was following the current recommendations on https://packaging.python.org/current/ and I assumed that `python setup.py bdist_wheel` would be sufficient. But I guess I should do `python setup.py sdist bdist_wheel` and upload them both (as suggested in https://packaging.python.org/distributing/#packaging-your-project)?

**Comment by daniellawrence** [comment]
The command that you found should resolve the issue that I am hitting.
```
python setup.py sdist bdist_wheel
```

Once uploaded, we should see an extra .tar.gz file for 1.0.0b1 on pypi

```
https://pypi.python.org/simple/flask-restless/
```

**Comment by jfinkels** [comment]
The Flask-Restless-1.0.0b1.tar.gz package (and its signature) should be available on PyPI now.
