### ISSUE TITLE
Loading model for chained AssociationProxy

### ISSUE THREAD

**Issue by Natureshadow** [jfinkels/flask-restless#578]
I have a model that uses chained associaiton proxies, like in this example: http://docs.sqlalchemy.org/en/latest/orm/extensions/associationproxy.html#composite-association-proxies

Restless fails to detect the remote model because `get_related_association_proxy_model` blindly assumes the remote is a plain property.

Unwrapping it recursively should do the trick:

```
    def get_related_association_proxy_model(attr):
        if isinstance(attr.remote_attr, AssociationProxy):
            prop = attr.remote_attr.property
            for attribute in ('mapper', 'parent'):
                if hasattr(prop, attribute):
                    return getattr(prop, attribute).class_
            return None
        else:
            return get_related_association_proxy_model(attr.remote_attr)
```

I monkey patched this code from within my applicaiton, and it seems to work. It still cannot discover arbitrary remote models, but at least it does not fail with an exception and works in some cases.

**Comment by Natureshadow** [comment]
Oh, I just see this is no more valid for the current Git version. I am using 0.17.0.

**Comment by jfinkels** [comment]
Great, thanks for looking into the problem! I'll close the issue.
