### ISSUE TITLE
Accept arbitrary queries

### ISSUE THREAD

**Issue by mwhite** [jfinkels/flask-restless#579]
Define a straightforward mapping between JSON and the SQLAlchemy expression language, and a function for formatting an arbitrary query result, so that arbitrary queries can be executed against the REST API.

Preferably, a JSON equivalent for SQLAlchemy Query methods (e.g. `join()`, `add_columns()`) could also be made.

**Comment by jfinkels** [comment]
Hi @mwhite! Can you give a brief example of the kind of interface you are suggesting here? I'm not sure exactly what you're envisioning. Thanks.

(cc @kopf, may be of interest to you)

**Comment by mwhite** [comment]
I'm looking to build a query builder UI that's aware of Flask-Restless endpoints / tables, so something like

```python
select([func.count(Foo.bar), Foo.name]).group_by(Foo.name).order_by(Foo.name)
```
```json
{
  "type": "select",
  "froms": [
    {"type": "function", "value": "count", "args": [{"type": "column", "value": "Foo.bar"}]},
    {"type": "column", "value": "Foo.name"}
  ],
  "methods": [
    {"type": "group_by", "value": {"type": "column", "value": "Foo.name"}},
    {"type": "order_by", "value": {"type": "column", "value": "Foo.name"}}
  ]
}
```

Or

```python
session.query(Foo).join(Bar).options(load_only(Foo.name))
```

```json
{
  "froms": [{"type": "class", "name": "Foo"}],
  "methods": [
    {"name": "join", "value": {"type": "class", "value": "Bar"}},
    {"name": "options", "value": {"type": "load_only", "value": {"type": "column", "value": "Foo.name"}}}
  ]
}
```

returning 

```js
[
  {"name": "asdf",
   "bars": [ {x: 1, y: 2}, /*...*/ ]
  },
 /*...*/
]
```

I recognize this is mostly orthogonal to the current functionality provided by Flask-Restless, and doing it correctly would probably require some non-trivial translation between endpoint names and classes and validating column visibility (if wishing to respect the columns specified for endpoints), but I was planning to use the standard Flask-Restless anyway in the same UI so wanted to see how you'd feel about this.

**Comment by mwhite** [comment]
(A programmatic interface unlikely to be used by developers for individual queries -- hopefully!)

**Comment by jfinkels** [comment]
I think this may be too far out-of-scope for Flask-Restless, whose (rather narrow) aim is to be a JSON API-compatible server (as of version 1.0.0b1) for Flask-SQLAlchemy models. The interface you are describing is becoming quite generic, which I decided was *not* the design goal of Flask-Restless.

I do see how it might be useful to use some of the machinery provided by Flask-Restless to build such an interface (for example, using the [global helper functions][1]). So I think this would be better as a separate project on top of Flask-Restless. But let me know if there's some way I can help or Flask-Restless can facilitate support.

[1]: http://flask-restless.readthedocs.io/en/latest/api.html#global-helper-functions

**Comment by mwhite** [comment]
Ok, thanks.  I may have actually requested something like this a couple years ago, in which case I apologize.

I'll probably look into creating this myself as an extension to Flask-Restless using those functions.
