### ISSUE TITLE
BetterJSONEncoder in tests is not simplejson

### ISSUE THREAD

**Issue by Natureshadow** [jfinkels/flask-restless#583]
The test suites fail because the JSONEncoder that is extended to BetterJSONEncoder in tests/helpers.py is not from simplejson, whereas the JSONEncoder used by Flask is.

Changing "from json import JSONEncoder to" "from simplejson import JSONEncoder" (and probably explicitly depending on simplejson) solves the issue.

**Comment by jfinkels** [comment]
Thanks for reporting this! I'd rather inherit the `json` implementation from Flask if at all possible, so Flask-Restless doesn't have to check whether simplejson/json can be imported. I have done this in the code where you see `from flask import json`. Can we do `from flask.json import JSONEncoder`?

**Comment by Natureshadow** [comment]
I'll shortly do a pull request ☺

**Comment by jfinkels** [comment]
It may be worth checking whether there are any other places in the code where we import from `json` instead of `from flask import json`.

**Comment by Natureshadow** [comment]
I did check that ☺.

**Comment by Natureshadow** [comment]
Oh, but now I see - in the tests, we could also use the JSONEncoder already imported by flask.json instead of doing the check for simplejson on our own, right?

**Comment by Natureshadow** [comment]
OK, simply using flask.json.JSONEncoder for feriving BetterJSONEncoder indeed does the trick.

Note that I mixed in another fix, because the .helpers module uses sys without importing it.
