### ISSUE TITLE
How to include related columns in apimanager

### ISSUE THREAD

**Issue by tzimme** [jfinkels/flask-restless#589]
Hello,

before updating to flask-restless 1.0.0b1, i could just add columns form a related table to the api-response by adding "include_columns=['column_from_related_table']" to create_api()

Now the relation is included by default, but only type and id are shown.

How can i add additional columns from a relation to create_api()?

**Comment by Natureshadow** [comment]
Did you mean `include_columns=["foo.bar"]`, where `foo` is a relation to another model and `bar` is an attribute of that model?

**Comment by jfinkels** [comment]
Flask-Restless is now following the [JSON API][1] format. In this format, the primary data coming from a request like `GET /person/1` is a [resource object][2] under the `data` element, and the `relationships` element includes only the [resource identifier objects][3] for the related objects. If a client wants information about those related elements, it can either fetch them directly using the information from the resource identifier objects or it can request that the server [includes the related resources][4].

[1]: http://jsonapi.org/
[2]: http://jsonapi.org/format/#document-resource-objects
[3]: http://jsonapi.org/format/#document-resource-identifier-objects
[4]: http://flask-restless.readthedocs.io/en/latest/includes.html

**Comment by jfinkels** [comment]
You can alternately customize the resource serialization to serialize the related objects manually. See http://flask-restless.readthedocs.io/en/latest/serialization.html.
