### ISSUE TITLE
Status 400: Unable to decode data

### ISSUE THREAD

**Issue by tzimme** [jfinkels/flask-restless#593]
Hello,

i'm trying to send the json I got from the api back via PATCH, but I get  a status 400: "Unable to decode data"

```
curl -i -X PATCH -H "Accept:application/vnd.api+json" http://localhost:5000/api/user/1 -H "Content-Type: application/vnd.api+json, application/json" -d /tmp/1
HTTP/1.0 400 BAD REQUEST
Content-Type: application/vnd.api+json
Vary: Accept
Content-Type: application/vnd.api+json
Content-Length: 281
Server: Werkzeug/0.11.11 Python/3.5.2+
Date: Fri, 07 Oct 2016 09:06:09 GMT

{
  "errors": [
    {
      "code": null, 
      "detail": "Unable to decode data", 
      "id": null, 
      "links": null, 
      "meta": null, 
      "source": null, 
      "status": 400, 
      "title": null
    }
  ], 
  "jsonapi": {
    "version": "1.0"
  }, 
  "meta": {}
}
```

`

> ERROR in base [/home/tzimme/.local/lib/python3.5/site-packages/flask_restless/views/base.py:726]:
> ## Expecting value: line 1 column 1 (char 0)
> 
> Traceback (most recent call last):
>   File "/home/tzimme/.local/lib/python3.5/site-packages/flask_restless/views/resources.py", line 572, in patch
>     data = json.loads(request.get_data()) or {}
>   File "/home/tzimme/.local/lib/python3.5/site-packages/flask/json.py", line 149, in loads
>     return _json.loads(s, **kwargs)
>   File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 533, in loads
>     return cls(encoding=encoding, **kw).decode(s)
>   File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
>     obj, end = self.raw_decode(s)
>   File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
>     return self.scan_once(s, idx=_w(s, idx).end())
> simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jfinkels** [comment]
Hi @tzimme. The data in your PATCH request must be a valid JSON object. Your data seems to be `/tmp/1`, which is not valid JSON.
