### ISSUE TITLE
Possible to EXTRACT(MONTH from birthday)?

### ISSUE THREAD

**Issue by joshuapowell** [jfinkels/flask-restless#595]
Question: Is it possible to pass Flask-Restless functions like `EXTRACT(MONTH from birthday)` as filter `name`?

This works:
```
{"filters":[{"name":"birth_date","op":"eq","val":"2010-10-01"}]}
```

This gives me a "400: Unable to construct query", because of course my model doesn't have ""EXTRACT(MONTH from birth_date)" as a field name:
```
{"filters":[{"name":"EXTRACT(MONTH from birth_date)","op":"eq","val":"10"}]}
```

This gives me a "400: Unable to construct query":
```
{"filters":[{"name":"MONTH(birth_date)","op":"eq","val":"10"}]}
```

This gives me a "400: DataError invalid..."
```
{"filters":[{"name":"birth_date","op":"eq","val":"October"}]}
```

This gives me a "400: Programming Error operator does not exist":
```
{"filters":[{"name":"birth_date","op":"eq","val":10}]}
```

I just was hoping it was possible to do through using the Postgres function. If I need to write a `preprocessor` for this, then no big deal.

**Comment by joshuapowell** [comment]
I have continued reading and rereading the documentation. Prior to writing my above question, I had discovered this documentation http://flask-restless.readthedocs.io/en/latest/requestformat.html#date-and-time-fields

The idea that one can use functions in the `"val"` of a filter like `CURRENT_TIMESTAMP`, `CURRENT_DATE`, or `LOCALTIMESTAMP` gave me a glimmer of hope. Still no luck though.

**Comment by jfinkels** [comment]
This is a little beyond the capability of the search functionality for now, it is quite simple. One workaround might be to create a hybrid property on your model and then filter on that property.

**Comment by joshuapowell** [comment]
I assumed. I ended up creating a preprocessor that extracts and saves the data into a separate `birth_month` field. My preprocessor looks like this:

```
import dateutil.parser as parser

def preprocessor_put_single(data=None, **kw):

    if data.get('birth_date'):
      birthday_date_object = parser.parse(data.get('birth_date'))
      data['birth_month'] = birthday_date_object.month

```
