### ISSUE TITLE
python: cannot import name DefaultSerializer

### ISSUE THREAD

**Issue by guambejr** [jfinkels/flask-restless#598]
Hi, I'm trying to run the example, but it fails to load DefaultSerializer and DefaultDeserializer from flask_restless.

I'm using python 2.7.12 and flask-restless-0.17.0.

Can you assist?

**Comment by jfinkels** [comment]
Hi @guambejr, the serializer/deserializer pattern only appears in version 1.0.0b1 or later. Note the difference between http://flask-restless.readthedocs.io/en/latest/ and http://flask-restless.readthedocs.io/en/stable/.

**Comment by guambejr** [comment]
Yes, I see. 
Thanks.

**Comment by pwaldo2** [comment]
Hi, I'm having the same problem but I have 1.0.0b1:

$ python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import flask_restless
>>> flask_restless.__version__
'1.0.0b1'
>>> from flask_restless import DefaultSerializer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'DefaultSerializer'

My goal is to use marshmallow-jsonapi for serialization and wanted to follow your example

**Comment by jfinkels** [comment]
In 1..0.0b1 the `DefaultSerializer` class is importable as `from flask_restless.serialization import DefaultSerializer".
