### ISSUE TITLE
create_api_blueprint() got an unexpected keyword argument 'include_columns'

### ISSUE THREAD

**Issue by guambejr** [jfinkels/flask-restless#601]
Hi, I'm using flask-restless for restful API for some time on my app. After a few changes on my Models, and views (added an endpoint using @app.route for serving images) the app doesn't start. The error message is as follows:

`  File "manage.py", line 12, in <module>
    app = create_app('dev')
  File "/home/me/python/dev/projs/sis/__init__.py", line 26, in create_app
    from . import views
  File "/home/me/python/dev/projs/sis/views.py", line 36, in <module>
    include_columns=['id'])
  File "/usr/lib/python2.7/site-packages/flask_restless/manager.py", line 891, in create_api
    blueprint = self.create_api_blueprint(blueprint_name, *args, **kw)
TypeError: create_api_blueprint() got an unexpected keyword argument 'include_columns'
`

NOTE:**I've removed all other columns from the include_columns list expect for the id and still fails to start, referencing the always the last column of the list on the logs.**

NOTE2: the app runs when I comment out the **api_manager.create_api(), and ran OK with the same configuration hours ago.**

Can you assist?

**Comment by jfinkels** [comment]
As in issue #598, the `include_columns` keyword argument no longer exists as of version 1.0.0b1. Use the `only` keyword argument instead, or perhaps `additional_attributes`. See https://flask-restless.readthedocs.io/en/latest/sparse.html for more information.

**Comment by guambejr** [comment]
thanks for your prompt reply.
I'll upgrade to 1.0.0b1. Is it production ready??

I hope I won't have to "revolutionize" my create_api() configuration in order to run.

**Comment by jfinkels** [comment]
See the pip documentation for information on [installing packages][1].

The latest version of Flask-Restless is not production-ready, the `b` in the version number indicates that it is a public beta version, which means there are still some known issues.

[1]: https://pip.pypa.io/en/stable/user_guide/#installing-packages

**Comment by guambejr** [comment]
I'll do that.
Thanks!

**Comment by asmodeusmax** [comment]
try exlude_columns 
```

1. def create_api_blueprint(self, model, app=None, methods=READONLY_METHODS,
2.                              url_prefix='/api', collection_name=None,
3.                              allow_patch_many=False, allow_delete_many=False,
4.                              allow_functions=False, exclude_columns=None,
5.                              include_columns=None, include_methods=None,
6.                              validation_exceptions=None, results_per_page=10,
7.                              max_results_per_page=100,
8.                              post_form_preprocessor=None, preprocessors=None,
9.                              postprocessors=None, primary_key=None,                                                                                          
10.                              serializer=None, deserializer=None):
11.                             ...

```

line 323 in flask_restless/manager.py
