### ISSUE TITLE
String formatting Error flask_restless.search.SearchParameters.__repr__

### ISSUE THREAD

**Issue by kannor** [jfinkels/flask-restless#628]
`junction` arg  [here](https://github.com/jfinkels/flask-restless/blob/0.17.0/flask_restless/search.py#L294)   value was passed [here](https://github.com/jfinkels/flask-restless/blob/0.17.0/flask_restless/search.py#L295)

**Comment by jfinkels** [comment]
I don't think this is still an issue in the development version.
