### ISSUE TITLE
Optional relationship rules

### ISSUE THREAD

**Issue by cburmeister** [jfinkels/flask-restless#645]
Is there a way to optionally generate the "relationship" rules for a `SQLAlchemy` model?

```
>>> self.app.url_map
Map([
 <Rule '/v1/offers' (OPTIONS) -> offersapi0.sell_offersapi>,
 <Rule '/v1/offers/<instid>/<relationname>/<relationinstid>' (GET, HEAD, OPTIONS) -> offersapi0.sell_offersapi>,
 <Rule '/v1/offers/<instid>/<relationname>' (GET, HEAD, OPTIONS) -> offersapi0.sell_offersapi>,
 <Rule '/v1/offers/<instid>' (GET, HEAD, OPTIONS) -> offersapi0.sell_offersapi>,
 <Rule '/v1/offers' (GET, HEAD, OPTIONS) -> offersapi0.sell_offersapi>
])
```

My model has no relationships -- how do I prevent `flask-restless` from registering these:
```
<Rule '/v1/offers/<instid>/<relationname>/<relationinstid>' (GET, HEAD, OPTIONS) -> offersapi0.sell_offersapi>,
<Rule '/v1/offers/<instid>/<relationname>' (GET, HEAD, OPTIONS) -> offersapi0.sell_offersapi>,
```

Here is an example model:
```
class Offer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
```

The *only* rules I want registered with the application are:
```
>>> self.app.url_map
Map([
 <Rule '/v1/offers' (OPTIONS) -> offersapi0.sell_offersapi>,
 <Rule '/v1/offers/<instid>' (GET, HEAD, OPTIONS) -> offersapi0.sell_offersapi>,
 <Rule '/v1/offers' (GET, HEAD, OPTIONS) -> offersapi0.sell_offersapi>
])
```

Related: Why are there *two* rules registered for `OPTIONS /v1/offers`?
```
Map([
 <Rule '/v1/offers' (OPTIONS) -> offersapi0.sell_offersapi>,
 <Rule '/v1/offers' (GET, HEAD, OPTIONS) -> offersapi0.sell_offersapi>
])
```

**Comment by jfinkels** [comment]
For your "Related:" issue, would you mind creating a separate GitHub issue for that (with minimal working example code)? Thanks a lot.

Now for your main issue: there is no way of preventing those endpoints from being created currently (see https://github.com/jfinkels/flask-restless/blob/master/flask_restless/manager.py#L807). But I suppose we could add a keyword argument to `APIManager.create_api` like `norelations=True` that disables those endpoints from being created. Would that satisfy your concerns?

**Comment by cburmeister** [comment]
@jfinkels could we determine that depending on if the model has any defined relationships?
