### ISSUE TITLE
lasttest version don`t support subdomain

### ISSUE THREAD

**Issue by LiGuangTian** [jfinkels/flask-restless#650]

**Comment by jfinkels** [comment]
Hi @LiGuangTian, can you provide more information about your problem? Can you provide a minimal working example that demonstrates the issue, explain what happens, and explain what you expected to happen?

**Comment by LiGuangTian** [comment]
It's just a little problem, for using server name and subdomain.if I wish use API manager in subdomain, I will add subdomain param when create blueprint.

**Comment by jfinkels** [comment]
I'm having some trouble understanding your problem. If you can provide the version of Flask-Restless you are using and some code that demonstrates the problem, please reopen this issue.

**Comment by LiGuangTian** [comment]
like this:

    api_manager = APIManager(app, flask_sqlalchemy_db=db, subdomain="test")
