### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by JonoB** [jfinkels/flask-restless#81]
The docs says "By default, no validation is performed by Flask-Restless; if you want validation, implement it yourself in your database models."

I'm very new to python, and I'm trying to figure out how to do validation in models. Are there any suggested extensions or documentation that you could point me to please?

**Comment by mahomahomaho** [comment]
Sorry for digging in buried thread, but you said "I didn't want to recode actions which other libraries (like WTForms) perform better". And my question is - how to plug WTForms into Flask restless?

I know how to validate form by such code:
```
@app.route("/api/validate", methods=['POST'])
def validate():
    fname, data = request.json
    form = None
    if fname == "events":
        form = EventsForm(formdata=MultiDict(mapping=data))
        form.validate()
    
    if form.errors:
        return jsonify({"errors": form.errors})

    return "OK"

```

but when I want to PUT/POST/PATCH changes into Events which is declared as
```
manager.create_api(Events, methods=["GET", "PUT"], exclude_columns=['repeat'],
                           include_methods=['repeat_desc'])
```
then I have no idea how to use WTForms with it.
